= Connect with hz-mc conf
:description: You can preconfigure the client connection to a cluster before you start Management Center, using the `hz-mc conf` tool.

Management Center starts a Hazelcast client for each cluster that it is connected to. You can preconfigure the client connection to a cluster before you start Management Center, using the `hz-mc conf` tool.

To connect Management Center to a Hazelcast cluster, using the `hz-mc conf` tool, you have two options:

- Provide the cluster name and member addresses.
- Provide the path to a client configuration file in XML or YAML format. (Recommended for more complex configurations.)
+
NOTE: If you enabled TLS/SSL on a Hazelcast cluster, you must use this option to configure the client TLS settings. For more information about TLS configuration, see xref:{page-latest-supported-hazelcast}@hazelcast:security:tls-ssl.adoc[TLS] in the Platform documentation.

== Before you begin

Make sure that Management Center is not running. If you execute a CLI command while Management Center is running, you will see the following error: `Could not lock home directory`.

For a getting started guide, see xref:mc-conf.adoc[].

== Configure a cluster connection

. To provide the cluster name and member addresses, use the following:
+
```bash
hz-mc conf cluster add -cn={cluster name} -ma={member addresses}
```
+
You should see:
+
```
Successfully added Cluster Config.
```

. To provide the path to a client configuration file, use the following:
+
```bash
hz-mc conf cluster add --client-config={path to file}
```
+
You should see:
+
```
Successfully added Cluster Config.
```
+
For help creating a client configuration file, see the link:https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-full-example.xml[full example references on GitHub]


. Start Management Center.

To connect to another cluster, repeat these steps.

NOTE: When connecting to multiple clusters from the same instance of Management Center, make sure that the cluster names are unique. Management Center does not support simultaneous connections to more than one cluster with the same cluster name.

== Remove a cluster connection

To remove an existing connection to a cluster, use the following:

```bash
hz-mc conf cluster remove -cn={cluster name}
```

You should see:

```
Successfully removed Cluster Config.
```

== Use --force

=== cluster add --force

Use the `-f` / `--force` flag to make `cluster add` idempotent:

* If no cluster with the given name is configured, the cluster is added.
* If a cluster with the same name is already configured with identical settings, the command succeeds without making any changes.
* If a cluster with the same name is already configured with different settings, the existing configuration is overwritten.

This removes the need to explicitly run `cluster remove` before re-adding a cluster.

=== cluster remove --force

Use the `-f` / `--force` flag to make `cluster remove` idempotent. The command succeeds even if no cluster with the given name is configured.

== Next steps

For the full reference of `mc-cli`, see xref:mc-conf.adoc[]

You can also use the CLI to preconfigure a security provider, including dev mode. This allows you to automate the setup of Management Center without needing to interact with the UI.
