= Enterprise licenses
:description: To use some features in Management Center, you need an Enterprise license.
:page-aliases: ROOT:managing-licenses.adoc

{description}

== Licensed features

Management Center requires a valid Enterprise license for the following:

* Clustered JMX
* Clustered REST API
* Cluster Client Filtering
* Prometheus Exporter
* Displaying metrics for more than three cluster members
* Healthcheck

To use these features in Management Center, you must install (in Management Center) either an Enterprise license for Management Center or an Enterprise license for Hazelcast Platform.

As well as these Management Center features, you need an Enterprise license for Hazelcast Platform on your cluster to use the following features in Management Center:

* WAN Replication
* Persistence (Hot Restart)
* Rolling Upgrade

== View cluster licenses

To view details about an Enterprise license for Hazelcast Platform that's installed on your cluster, see xref:clusters:cluster-license.adoc[].

== Update Management Center licenses

To update an Enterprise license for Management Center, see xref:updating-mc-license-ui.adoc[].

== Update cluster licenses at runtime

You can use Management Center to update an existing Enterprise license in your Hazelcast cluster. See xref:clusters:update-config.adoc[].

Or, for other ways to update a license, see the xref:{page-latest-supported-hazelcast}@hazelcast:deploy:enterprise-licenses.adoc[Hazelcast Platform documentation].