= Local security provider
:description: You can use the local security provider to control authentication and authorization in Management Center. With this security provider, user accounts are stored in Management Center's database.

{description}

== Set up the local security provider

To set up the local security provider, you need to create an admin user, using either the UI or the `hz-mc conf` tool.

[tabs] 
====
UI::
+
--

To set up the local security provider in the UI, go to *Settings* > *Security Providers* > *Local*.

--
mc-conf::
+
--
To create a new user with `hz-mc conf`, use the following command. Replace the `<username>` placeholder with your username. For details about the `mc-conf` tool, see xref:mc-conf.adoc[].

.Linux and Mac
```bash
hz-mc conf user create -n <username> -r admin -p 
```

.Windows
```bash
mc-conf.bat user create -n <username> -r admin -p 
```
--
====

* **Username:** Username for the initial administrator user account.
* **Password:** Password for the initial administrator user account.

Passwords *must* include the following:

* Minimum of 8 characters
* At least one letter
* At least one digit
* At least one special character, which is not a letter, digit or space

Passwords *must not* include the following:

* The username
* Two or more of the same letter following each other.
* A 3-character or longer sequence of letters following or preceding each other such as "abc" or "fed".
* A 3-character or longer sequence of digits following or preceding each other such as "123" or "987".

== Create users

To create additional users, admin users can use the UI or you can use the `hz-mc conf` tool.

When creating users, be sure to give them a valid role. See xref:user-management.adoc[].

[tabs] 
====
UI::
+
--

To set up the local security provider in the UI, go to *Settings* > *Security Providers* > *Local*.

--
mc-conf::
+
--
To create a new user with `hz-mc conf`, use the following command. Replace the `<username>` placeholder with your username.

.Linux and Mac
```bash
hz-mc conf user create -n <username> -r admin -p 
```

.Windows
```bash
mc-conf.bat user create -n <username> -r admin -p 
```
--
====

== Use a dictionary to prevent weak user passwords

To prevent certain words from being included in user
passwords, you can use a dictionary.

. Create a text file that contains the words that you want to prevent.
+
Each word must be on a new line and must contain at least three characters.

. Start Management Center with the `hazelcast.mc.security.dictionary.path`
property where the path points to your text file.

Words that are shorter
than four characters are ignored to avoid blocking too many password
combinations. You can configure
the minimum length of words by starting Management Center with the
`hazelcast.mc.security.dictionary.minWordLength`
property.

[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
hz-mc start -Dhazelcast.mc.security.dictionary.path=/usr/MCtext/pwd.txt \
     -Dhazelcast.mc.security.dictionary.minWordLength=3
----
--
Windows::
+
--
[source,bash,subs="attributes+"]
----
mc-start.cmd -Dhazelcast.mc.security.dictionary.path=/usr/MCtext/pwd.txt ^
     -Dhazelcast.mc.security.dictionary.minWordLength=3
----
--
====

== Change user passwords

To change user passwords in the local security provider, admin users can use the UI or you can use the `hz-mc conf` tool.

[tabs] 
====
UI::
+
--

. Go to *Settings* > *Users*.

. Click *Edit* in the row of the user whose password you want to change.

. Click *Change Password*.

--
hz-mc-conf::
+
--
Use the following `hz-mc conf` command. Replace the `<username>` placeholder with your username.

.Linux and Mac
```bash
hz-mc conf user update-password -n <username> -p

```

.Windows
```bash
mc-conf.bat user update-password -n <username> -p
```

NOTE: If you're on Linux or Mac devices, enclose passwords in single quotes only if you use the `--password` option. If you use the `-p` flag, do not use single quotes in the interactive prompt.
--
====

== Next steps

For details about the `hz-mc conf` tool, see xref:mc-conf.adoc[].
