= System Properties
:description: You can use system properties to configure all aspects of Management Center, from JMX to the home directory and feature flags. System properties give administrators and developers the power to tweak settings at startup without having to configure anything in the UI.
:page-aliases: ROOT:configuring.adoc

{description}

If you start Management Center using any of the following methods, you can use the `JAVA_OPTS` environment variable to set system properties:

- Docker environments
+
TIP: You may also need to use other environment variables. For the Docker reference, see link:https://hub.docker.com/r/hazelcast/management-center[DockerHub].
- `mc-conf` tool
- Start scripts included with Hazelcast Platform or Management Center such as `mc-start`.

You can use system properties to configure both Management Center and Management Center's client connection strategy on startup.

== Management Center Configuration

.System properties for Management Center
[cols="25%m,50%a,25%a"]
|===
|Property|Description|Example

|[[hazelcast-mc-allowmultiplelogin]]hazelcast.mc.allowMultipleLogin
|Whether a user can log into an account in Management Center on multiple devices in different locations at the same time. Default: `false`. See xref:sessions.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.allowMultipleLogin=true -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-auditlog-enabled]]hazelcast.mc.auditlog.enabled
|Whether Management Center logs auditable events. See xref:logging.adoc#audit-logging[Audit Logging]. Default: `false`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.auditlog.enabled=true \
-jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-configreplacer-class]]hazelcast.mc.configReplacer.class
|Full class name of a variable replacer to use. See xref:variable-replacers.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.configReplacer.class=com.hazelcast.webmonitor.configreplacer.EncryptionReplacer \
-jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-configreplacer-failifvaluemissingissing]]hazelcast.mc.configReplacer.failIfValueMissing
|Whether the
configuration loading process stops when a replacement value is missing. Default: `true`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.configReplacer.failIfValueMissing=true \
-jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-contextpath]]hazelcast.mc.contextPath
|Prefix of all URL paths in Management Center. Default: `' '` (empty).
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.contextPath=hazelcast-mc \
-jar hazelcast-management-center-{full-version}.jar
----

In this example, the URL for Management Center would be `\http:localhost:8080/hazelcast-mc`.

|[[hazelcast-mc-disablehostnameverification]]hazelcast.mc.disableHostnameVerification
|Whether Management Center does not verify the hostname of signed TLS/SSL certificates. Default: `false`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.disableHostnameVerification=true -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-disableloginperiodmultiplier]]hazelcast.mc.disableLoginPeriodMultiplier
|Multiplier used for extending
the disabled login period in case the failed login attempts continue after the disabled login
period expires. Default: `10`. See xref:sessions.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.disableLoginPeriodMultiplier=20 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-exclude-cipher-suites]]hazelcast.mc.exclude.cipher.suites
|A comma separated list of cipher suites to be excluded from the list of supported ciphers in Management Center. Wildcards are supported.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.exclude.cipher.suites=^.*_(MD5\|SHA\|SHA1)$,^TLS_RSA_.*$,^.*_NULL_.*$ -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-failedattemptsbeforedisablelogin]]hazelcast.mc.failedAttemptsBeforeDisableLogin
|Number of failed
login attempts that Management Center allows before disabling logins. Default: `3`. See xref:sessions.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.failedAttemptsBeforeDisableLogin=1 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-forcelogoutonmultiplelogin]]hazelcast.mc.forceLogoutOnMultipleLogin
|Whether Management Center forces users to log out when other users try to log into the same account. Default: `false`. See xref:sessions.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.forceLogoutOnMultipleLogin=true -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-forwarded-requests-enabled]]hazelcast.mc.forwarded.requests.enabled
|Whether Management Center reads `X-Forwarded-*`
headers from reverse proxies. Default: `true`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.forwarded.requests.enabled=false -jar hazelcast-management-center-{full-version}.jar
----

|[[enabling-health-check-endpoint]][[hazelcast-mc-healthcheck-enable]]hazelcast.mc.healthCheck.enable
|Whether the `/health` endpoint is enabled on port <<hazelcast-mc-http-port,`hazelcast.mc.http.port`>> + 1. Default: `false`. This endpoint is always served over HTTP, regardless of any TLS/SSL settings. This endpoint responds with `200 OK` HTTP
status code if Management Center is running.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.healthCheck.enable=true -jar hazelcast-management-center-{full-version}.jar
----

In this example, the health check would be available at `\http://localhost:8081/health`.

|[[hazelcast-mc-home]]hazelcast.mc.home
|Home directory where metrics, executed SQL queries, and configuration settings are saved. See xref:configuring.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.home=/home/management-center -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-hostaddress]]hazelcast.mc.hostAddress
|Network address that Management Center is reachable on. Default: `0.0.0.0` (all network interfaces).
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.hostAddress=127.0.1.1 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-http-port]]hazelcast.mc.http.port
|HTTP port for Management Center. Default: `8080`.
|
[source,bash,subs="attributes+"]
----
java hazelcast.mc.http.port=80 -jar hazelcast-management-center-{full-version}.jar
----

In this example, the URL for Management Center would be `\http:localhost:80`.

|[[hazelcast-mc-include-cipher-suites]]hazelcast.mc.include.cipher.suites
|A comma separated list of cipher suits to be included in the list of supported ciphers in Management Center. Wildcards are supported.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.include.cipher.suites=^SSL_.*$ -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-initialdisableloginperiod]]hazelcast.mc.initialDisableLoginPeriod
|Initial duration for the disabled
login period in seconds. Default: `5`. See xref:sessions.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.initialDisableLoginPeriod=50 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-ldap-timeout]]hazelcast.mc.ldap.timeout
|Timeout in milliseconds for Active Directory and LDAP search queries. Default: `3000`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.ldap.timeout=4000 \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[starting-with-a-license]][[hazelcast-mc-license]]hazelcast.mc.license
|Enterprise license. When this property is set, the license takes precedence
over one that is set in the user interface, and you cannot update the license in the UI. For more details about licenses, see See xref:license-management.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.license={license key} -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-lock-skip]]hazelcast.mc.lock.skip
|Whether the `mc-conf` tool does not check for an `mc.lock` file in the home directory. Default: `false`. See xref:mc-conf.adoc#skipping-the-check-for-a-lock-file[Skipping the Check for a Lock File]
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.lock.skip=true -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-maxdisableloginperiod]]hazelcast.mc.maxDisableLoginPeriod
|Maximum amount of time for the disable
login period. By default, the
disabled login period is unlimited.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.maxDisableLoginPeriod= \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[disk-usage-config]][[hazelcast-mc-metrics-disk-ttl-duration]]hazelcast.mc.metrics.disk.ttl.duration
|Time-to-Live (TTL) in ISO-8601-based durations format for each record in the metrics persistence. Default: `P1D` (one day). This value must be positive. See xref:historical-metrics.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.metrics.disk.ttl.duration=P2D -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-phone-home-enabled]]hazelcast.mc.phone.home.enabled
|Whether Management Center sends usage data to the Hazelcast phone home server. Default: `true`. See xref:phone-homes.adoc[].
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.phone.home.enabled=false \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-prometheusexporter-enabled]]hazelcast.mc.prometheusExporter.enabled
|Whether to expose all metrics to the `/metrics` endpoint to be consumed by Prometheus. All metrics at the endpoint include the `hz_` prefix. Default: `false`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.prometheusExporter.enabled=true \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-prometheusExporter-filter-metrics-included]]hazelcast.mc.prometheusExporter.filter.metrics.included
|Metrics to include in the `/metrics` endpoint. Default: `' '` (empty).
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.prometheusExporter.filter.metrics.included=hz_topic_totalReceivedMessages,hz_map_totalPutLatency \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-prometheusexporter-filter-metrics-excluded]]hazelcast.mc.prometheusExporter.filter.metrics.excluded
|Metrics to exclude from the `/metrics` endpoint. Default: `' '` (empty).
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.prometheusExporter.filter.metrics.excluded=hz_os_systemLoadAverage,hz_memory_freeHeap \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-prometheusexporter-port]]hazelcast.mc.prometheusExporter.port
|Port on which the `/metrics` endpoint is exposed.
|
[source,bash,subs="attributes+"]
----
java -jar -Dhazelcast.mc.prometheusExporter.enabled=true \
  -Dhazelcast.mc.prometheusExporter.port=2222 \
  -jar hazelcast-management-center-{full-version}.jar
----

In this example, the `/metrics` endpoint would be available on port 2222: `\http://localhost:2222/metrics`.

|[[hazelcast-mc-security-dictionary-minWordLength]]hazelcast.mc.security.dictionary.minWordLength
|Minimum length that words in the dictionary must contain. Default: `3`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.security.dictionary.path=/usr/MCtext/pwd.txt \
     -Dhazelcast.mc.security.dictionary.minWordLength=3 \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-security-dictionary-path]]hazelcast.mc.security.dictionary.path
|Path to a text file that contains words that cannot be included in user passwords. 
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.security.dictionary.path=/usr/MCtext/pwd.txt \
     -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-session-timeout-seconds]]hazelcast.mc.session.timeout.seconds
|Number of seconds that a session can remain inactive before it is invalid and the user must log in again. Default `1800`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.session.timeout.seconds=60 -jar hazelcast-management-center-{full-version}.jar
----

|[[metadata-polling-config]][[hazelcast-mc-state-reschedule-delay-millis]]hazelcast.mc.state.reschedule.delay.millis
|Duration in milliseconds that Management Center waits before requesting metadata from a Hazelcast cluster. Metadata includes a
list of all data structures and their configurations. Default: 1000.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.state.reschedule.delay.millis=2000 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-excludeprotocols]]hazelcast.mc.tls.excludeProtocols
|A comma separated list of TLS/SSL protocols to be excluded from the list of supported protocols in Management Center.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.excludeProtocols=SSLv3 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-openssl]]hazelcast.mc.tls.openSsl
|Allow Management Center to use https://github.com/google/conscrypt/[Google's Conscrypt SSL] that is built on their fork of OpenSSL, BoringSSL. Default: `false`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.openSsl=true -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-enabled]]hazelcast.mc.tls.enabled
|Whether TLS/SSL is enabled. Default: `false`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.enabled=true -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-keystore]]hazelcast.mc.tls.keyStore
|Path to a keystore.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.keyStore=/keys/mc.keystore -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-keystorepassword]]hazelcast.mc.tls.keyStorePassword
|Password of the keystore in <<hazelcast-mc-tls-keystore, `hazelcast.mc.tls.keyStore`>>.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.keyStorePassword=mypassword123 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-truststore]]hazelcast.mc.tls.trustStore
|Path to a truststore. If the <<hazelcast-mc-tls-enabled, `hazelcast.mc.tls.enabled`>> system property is `true` and this value is empty, Management Center uses the system JVM's own truststore.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.trustStore=/truststores/mc.truststore -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-truststorepassword]]hazelcast.mc.tls.trustStorePassword
|Password of the truststore.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.trustStorePassword=mypassword123 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast.mc.tls.enableHttpPort]]hazelcast.mc.tls.enableHttpPort
|Whether the HTTP port in the <<hazelcast-mc-http-port, `hazelcast.mc.http.port`>> system property is redirected to the HTTPS port in the <<hazelcast-mc-https-port, `hazelcast.mc.https.port`>> system property.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.trustStorePassword=mypassword123 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-tls-mutualauthentication]]hazelcast.mc.tls.mutualAuthentication
|Whether clients connected to Management Center are authenticated:

* `REQUIRED`: If the client does not provide a keystore or the provided keys are not included in the Management Center's truststore, the client will not be authenticated.
* `OPTIONAL`: If the client does not provide a keystore, it will be authenticated. But, if the client provides keys that are not included in the Management Center's truststore, the client will not be authenticated.

Default: `OPTIONAL`.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.tls.mutualAuthentication=REQUIRED -jar hazelcast-management-center-{full-version}.jar
----


|===

[[client-config]]
== Client Connection Strategy Configuration

Use the following properties to configure the connection strategy of the Management Center client.

These properties apply to all clients that are started by Management Center.

.System properties for Management Center client
[cols="25%m,50%a,25%a"]
|===
|Property|Description|Example


|[[hazelcast-mc-client-max-backoff-millis]]hazelcast.mc.client.max.backoff.millis
|Upper limit of the backoff in milliseconds. Default: `30000`.
Values must be between 30000 and 600000.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.client.max.backoff.millis=486000 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-client-backoff-multiplier]]hazelcast.mc.client.backoff.multiplier
|Factor by which to multiply the backoff after
each failed retry. Default: `2`. Values must be between 1 and 10.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.client.backoff.multiplier=3 -jar hazelcast-management-center-{full-version}.jar
----

|[[hazelcast-mc-client-initial-backoff-millis]]hazelcast.mc.client.initial.backoff.millis
|Duration in milliseconds that Management Center waits after the first connection failure before retrying. Default: `1000`. Values must be between 1000 and 60000.
|
[source,bash,subs="attributes+"]
----
java -Dhazelcast.mc.client.initial.backoff.millis=2000 -jar hazelcast-management-center-{full-version}.jar
----

|===