= Updating an Enterprise License for Management Center
:description: You can use the UI to update a license.

An Enterprise license must be installed on Management Center to access Enterprise features and display metrics for more than three cluster members. 

{description}

== Before you Begin

You need a valid Enterprise license. You can get a trial license from the link:http://trialrequest.hazelcast.com/[Hazelcast website].

Make sure that Management Center was not started with the `hazelcast.mc.license` property. This property takes precedence over any license that is set in the UI.

This feature is available only to admin users.

== Updating the License

. Go to *Settings* > *License*.
+
You'll see the following:
+
- *License Key Hash*: SHA-256 hash of the key as a Base64 encoded string. The actual key is not displayed for security reasons.
- *Expires*: The date on which the license will expire.
- *Licensed Cluster Members*: The total number of members that the license supports and the current number of members running on the license.
- *License Type*: The type of license.
+
Warnings are displayed when a license expires within 30 days.

. Click *Update my license key*, enter your license key and click *Update License*.

The information on the page will be updated for the new license.

== Next Steps

xref:clusters:cluster-license.adoc[View the license that's installed on the Hazelcast cluster].

Use the REST API to xref:clustered-rest.adoc#retrieving-management-center-license-expiration-time[get details about license expiration times].

Start Management Center with the xref:system-properties.adoc#starting-with-a-license[`hazelcast.mc.license` system property] to override any Management Center Enterprise license for Management Center that's already installed.