= Variable Replacers

Variable replacers are used to replace custom strings in configuration. You can use variable replacers in command line arguments
or the xref:mc-conf.adoc[`mc-conf` tool].

For example, you can use variable replacers to mask sensitive information such as usernames and passwords.

A variable to be replaced takes the following form:

```
$<prefix> {"<masked-value"}
```

The `<prefix>` placeholder tells Management Center which replacer to use to replace in the value in the `<masked-value>` placeholder.

== Built-in Replacers

The following replacer classes are provided by Hazelcast as example
implementations of the `ConfigReplacer` interface.
Note that you can also implement your own replacers.

* `EncryptionReplacer`
* `PropertyReplacer`

Each example replacer is explained in the following sections

=== EncryptionReplacer

This example `EncryptionReplacer` replaces the encrypted variables with
its plain form. The secret key for encryption/decryption is generated from a
password which can be a value in a file and/or environment specific values,
such as MAC address and actual user data.

TIP: To see an example of how you can use the encryption replacer, see xref:serve-mc-over-https.adoc[].

The full class name is `com.hazelcast.webmonitor.configreplacer.EncryptionReplacer`
and the replacer prefix is `ENC`. Here are the properties used to configure
this example replacer:

* `hazelcast.mc.configReplacer.prop.cipherAlgorithm`: Cipher algorithm used for
the encryption/decryption. Its default value is AES.
* `hazelcast.mc.configReplacer.prop.keyLengthBits`: Length (in bits) of the
secret key to be generated. Its default value is 128.
* `hazelcast.mc.configReplacer.prop.passwordFile`: Path to a file whose content
should be used as a part of the encryption password. When the property
is not provided, no file is used as a part of the password. Its default value is null.
* `hazelcast.mc.configReplacer.prop.passwordNetworkInterface`: Name of the network interface
whose MAC address should be used as a part of the encryption password. When the
property is not provided no network interface property is used as a part of the password.
Its default value is null.
* `hazelcast.mc.configReplacer.prop.passwordUserProperties`: Specifies whether
the current user properties (`user.name` and `user.home`) should be used
as a part of the encryption password. Its default value is true.
* `hazelcast.mc.configReplacer.prop.saltLengthBytes`: Length (in bytes) of a
random password salt. Its default value is 8.
* `hazelcast.mc.configReplacer.prop.secretKeyAlgorithm`:  Name of the secret key
algorithm to be associated with the generated secret key. Its default
value is AES.
* `hazelcast.mc.configReplacer.prop.secretKeyFactoryAlgorithm`: Algorithm used
to generate a secret key from a password. Its default value is
PBKDF2WithHmacSHA256.
* `hazelcast.mc.configReplacer.prop.securityProvider`: Name of a Java Security
Provider to be used for retrieving the configured secret key factory and
the cipher. Its default value is null.

NOTE: Older Java versions may not support all the algorithms used as defaults.
Use the property values supported by your Java version.

== PropertyReplacer

`PropertyReplacer` replaces variables by properties with the given name.
Usually the system properties are used such as`${user.name}`.

The full class name is `com.hazelcast.webmonitor.configreplacer.PropertyReplacer`
and the replacer prefix is empty string ("").

== Implementing Custom Replacers

To create your own variable replacer implementations, you must implement the following three methods from the `ConfigReplacer` interface:

[source,java]
----
import java.util.Properties;

public interface ConfigReplacer {
    void init(Properties properties);
    String getPrefix();
    String getReplacement(String maskedValue);
}
----

To use a custom variable replacer, you must configure it, using one of the following options:

* Client configuration file
* System properties

A variable to be replaced takes the following form:

```
$<prefix> {"<masked-value>"}
```

The `<prefix>` placeholder is the value returned by the `getPrefix()` method and the `<masked-value>` placeholder is a value provided by the `getReplacement()` method, which replaces the whole variable string.