site:
  title: Documentation
  url: https://frosty-curran-1fc0c4.netlify.app/
  start_page: management-center:getting-started:overview.adoc
  robots: disallow
  keys:
    google_analytics: GTM-MQ59XD6
    docsearch_id: QK2EAH8GB0
    docsearch_api: ef7bd9485eafbd75d6e8425949eda1f5
    docsearch_index: prod_hazelcast_docs
    ai_search_id: 6b326171-dd1e-40c6-a948-1f9bb6c0ed52
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
    - url: https://github.com/hazelcast/hazelcast-docs
      start_paths:
        - home
        - tutorials
        - templates
      branches:
        - main
    - url: https://github.com/hazelcast/hz-docs
      branches:
        - main
        - v/*
      start_path: docs
    - url: https://github.com/hazelcast/hz-flow-docs
      branches:
        - main
      start_path: docs
    - url: https://github.com/hazelcast/imdg-docs
      branches:
        - v/*
      start_path: docs
    - url: https://github.com/hazelcast/imdg-docs
      branches:
        - archived-versions
      start_paths: docs/*
    - url: https://github.com/hazelcast/management-center-docs
      branches:
        - main
        - v/*
        - "!main"
      start_path: docs
    - url: https://github.com/hazelcast/management-center-docs
      branches:
        - archived-versions
      start_paths: docs/*
    - url: https://github.com/hazelcast/clc-docs
      branches:
        - v/*
      start_path: docs
    - url: https://github.com/hazelcast/hazelcast-platform-operator-docs
      branches:
        - main
        - v/*
      start_path: docs
    - url: https://github.com/hazelcast/jdbc-driver-docs
      branches:
        - main
      start_path: docs
    - url: https://github.com/hazelcast-guides/user-code-namespaces
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/cpsubsystem
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/stream-processing-fundamentals
      branches: main
      start_path: docs
    - url: https://github.com/hazelcast-guides/airline-connections
      branches: main
      start_path: docs
    - url: https://github.com/hazelcast-guides/Generating-Data-using-SQL
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/sql_stock_ticker_cloud
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/Stream-Processing-Intro
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast/cloud-docs
      branches:
        - main
      start_paths:
        - docs
        - tutorials
    - url: https://github.com/hazelcast-guides/client-failover
      branches: master
      start_paths: docs
    - url: https://github.com/hazelcast-guides/spring-boot-sample
      branches: master
      start_paths: docs
    - url: https://github.com/hazelcast-guides/serverless-fraud-detection
      branches: master
      start_paths: docs
    - url: https://github.com/hazelcast-guides/write-through-cache-mongodb-mapstore
      branches: master
      start_paths: docs
    - url: https://github.com/hazelcast-guides/standard-deviation-parallel-processing
      branches: master
      start_paths: docs
    - url: https://github.com/hazelcast-guides/stream-to-stream-joins
      branches: master
      start_paths: docs
    - url: https://github.com/hazelcast/hazelcast-cloud-maven-plugin
      branches: main
      start_path: docs
    - url: https://github.com/hazelcast-guides/caching-springboot-jcache
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-embedded-springboot
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/springboot-hibernate
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hibernate-jcache
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/istio
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/caching-micronaut
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes-embedded
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-embedded-microprofile
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-client-quarkus
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/springboot-webfilter-session-replication
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/caching-springboot
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/ecs-embedded
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/springboot-tomcat-session-replication
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/terraform-quickstarts
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes-external-client
      branches: main
      start_path: docs
    - url: https://github.com/hazelcast-guides/active-directory-authentication
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes-sidecar
      branches: main
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes-hpa
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes-ssl
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes-wan
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kubernetes
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/spring-session-hazelcast
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/ec2-cluster
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/Hazelcast-Embedded-with-Eureka-discovery
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/linkerd
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/consul
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/openfaas-hz-client
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-expose-externally
      branches: main
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-external-backup-restore
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-wan-replication
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-wan-sync
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-jet
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-jet-job-snapshot
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-tls
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-user-code-namespace
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/kafka-kerberos
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/serverless-trade-monitor-dashboard
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast/hazelcast-mono
      branches:
        - master
        - 5.5.z
      start_path: docs/rest
    - url: https://github.com/hazelcast/management-center
      branches:
        - master
        - 5.1.4
        - 5.2.1
        - 5.3.4
        - 5.4.1
        - 5.5.2
        - 5.6.0
        - 5.7.0
      start_path: antora
    - url: https://github.com/hazelcast-guides/csharp-client-getting-started
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/python-client-getting-started
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/java-client-getting-started
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/nodejs-client-getting-started
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/go-client-getting-started
      branches: master
      start_path: docs
    - url: https://github.com/hazelcast-guides/cpp-client-getting-started
      branches: master
      start_path: docs
ui:
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-component-order: hazelcast, management-center, cloud, *
    page-pagination: true
    page-experimental: true
    idprefix: ""
    idseparator: "-"
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    imdg-docs: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    imdg-ops-guide: https://hazelcast.com/resources/hazelcast-deployment-operations-guide/
    jet-docs: https://jet-start.sh/
    docs-archive: https://hazelcast.org/imdg/download/archives/
    hazelcast-cloud: Cloud
    page-cloud-console: https://cloud.hazelcast.com/
    ucn: User Code Namespaces
    ucd: User Code Deployment
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
  extensions:
    - ./node_modules/hazelcast-docs-tools/antora-macro/tabs-block.js
    - ./node_modules/hazelcast-docs-tools/antora-macro/swagger-ui-block-macro.js
