= Hazelcast Management Center Documentation
// Settings:
ifdef::env-github[]
:warning-caption: :warning:
endif::[]
// URLs:
:url-org: https://github.com/hazelcast
:url-contribute: https://github.com/hazelcast/hazelcast-docs/blob/develop/.github/CONTRIBUTING.adoc
:url-ui: {url-org}/hazelcast-docs-ui
:url-playbook: {url-org}/hazelcast-docs
:url-staging: https://infallible-gates-b7fd92.netlify.app/

image:https://img.shields.io/badge/Build-Staging-yellow[link="{url-staging}"]

This repository contains the Antora components for the Hazelcast Management Center documentation.

The documentation source files are marked up with AsciiDoc.

== Docs Structure

This section describes some important information about how this repository is structured:

- The component name, version, and start page are configured in each branch's `antora.yml` file.
- The navigation for all modules is stored in the ROOT module's `nav.adoc` file.
- The {url-playbook}[docs site playbook] instructs Antora to automatically build the site using content in the `main` branch as well as any branches that are prefixed with `v/`.

== Release Workflow

Documentation for new releases is hosted in versioned branches that are prefixed with `v/`. For example, content for the `4.2020.12` version is hosted in the `v/4.2020.12` tag. The `latest-dev` content is stored in the `main` branch.

The documentation build process is triggered whenever you create a new branch with the `v/` prefix, push to an existing `v/` branch, or push to the `main` branch.

. When you are ready to release, create a new release branch from the `main` branch and name it with the full version number that you are releasing. For example, if you are releasing version 4.2020.12, name the branch v/4.2020.12.
+
TIP: For guidance on writing content, see the {url-contribute}[contribution guidelines].

. In the `antora.yml` file of your release branch, update the `version` field with the version of Management Center that you are working on.
+
[source,yaml]
----
version: 4.2020.12
----
+
NOTE: As soon as you push to this branch, GitHub will trigger a new build of the site, which will include your new content.

. If you are releasing a new `latest` version, submit a pull request to the `develop` branch of the link:{url-playbook}[`hazelcast/hazelcast-docs`] repository to do the following:
+
- Update the `_redirects` file with your release version of IMDG.
+
NOTE: This file is where we alias the `latest` path in URLs.
+
[source,bash]
----
# Redirect latest management center alias to the latest version
/management-center/latest/*  /management-center/4.2020.12/:splat 200!
----
+
- Update the `search-config.json` file with your release version of IMDG.
+
NOTE: This file is where we specify which documentation version to index for the search.
+
[source,json]
----
{
  "index_name": "prod_hazelcast_docs",
  "start_urls": [
    {
      "url": "https://docs.hazelcast.com/management-center/(?P<version>.*?)/",
      "tags": [
        "management-center"
      ],
      "variables": {
        "version": ["4.2021.03"]
      },
----

. If you are releasing a new `latest-dev` version, do the following:
+
- In the `antora.yml` file of the `main` branch, increment the `version` field to the `latest-dev` version. For example, `4.2021.02-SNAPSHOT` becomes `4.2021.03-SNAPSHOT`.
- In the `develop` branch of the link:{url-playbook}[`hazelcast/hazelcast-docs`] repository, submit a pull request to update the `_redirects` file with the new `latest-dev` version of Management Center.
+
NOTE: This file is where we alias the `latest-dev` and `latest` paths in URLs.
+
[source,bash]
----
# Redirect latest-dev management center alias to the latest-dev version
/management-center/latest-dev/*  /management-center/4.2021.03-SNAPSHOT/:splat 200!
----

== GitHub Actions

To automate some elements of the build process, this repository includes the following GitHub Actions:

.GitHub Actions
[cols="m,a,a"]
|===
|File |Description |Triggers

|validate-site.yml
|Validates that all internal and external links are working
|On a pull request to the `master`, `archive`, and `v/` branches

|build-site.yml
|Builds the production documentation site by sending a build hook to Netlify (the hosting platform that we use)
|On a push to the `master` branch and any `v/` branches
|===

== Contributing

If you want to add a change or contribute new content, see our {url-contribute}[contributing guide].

To let us know about something that you'd like us to change, consider {url-org}/hazelcast-reference-manual/issues/new[creating an issue].
