[[cache_size]]
== Configuring the maximum cache size

You can configure the maximum size of the cache containing timestamped cluster states using the
`hazelcast.mc.cache.max.size` system property. This value is `768` by default. Decreasing this limit can
significantly lower the heap usage of Management Center in cases when the cluster contains a lot of maps.

=== Approximate heap usages

The tables below list reference data about the heap usage of Management Center, depending on the cluster member
count, map count in each member, and `hazelcast.mc.cache.max.size` setting.

.Heap usages with 2 cluster members
|===
| `hazelcast.mc.cache.max.size` | 2,000 maps | 4,000 maps | 6,000 maps

| 256
| 440 Mb
| 810 Mb
| 1,170 Mb

| 512
| 800 Mb
| 1,530 Mb
| 2,260 Mb

| 768
| 1,150 Mb
| 2,240 Mb
| 3,320 Mb
|===


.Heap usages with 10 cluster members
|===
| `hazelcast.mc.cache.max.size` | 2,000 maps | 4,000 maps | 6,000 maps

| 256
| 1,750 Mb
| 3,560 Mb
| 5,290 Mb

| 512
| 3,530 Mb
| 6,960 Mb
| 10,030 Mb

| 768
| 4,340 Mb
| 9,770 Mb
|
|===

It is not recommended to change the cache size unless the cluster has a large number of distributed data structures which may cause Management Center to run out of heap memory.
Setting too low a value for `hazelcast.mc.cache.max.size` can be detrimental to the level of detail shown within Management Center, especially when it comes to graphs.
