
[[clustered-rest]]
== Clustered REST via Management Center


[blue]#Hazelcast IMDG Enterprise#


The Clustered REST API is exposed from Management Center to allow you to monitor clustered statistics of distributed objects.

=== Enabling Clustered REST

To enable Clustered REST on your Management Center, pass the following system property at startup. This property is disabled by default.

```bash
-Dhazelcast.mc.rest.enabled=true
```

=== Clustered REST API Root 

The entry point for Clustered REST API is `/rest/`.

This resource does not have any attributes.

NOTE: All parameters that are used in REST API URLs, like cluster names and distributed data structure names, must be
https://en.wikipedia.org/wiki/Percent-encoding[URL encoded] when composing a valid request for Clustered REST.
Such parameters are marked in braces (`{` and `}`) in URL description for each endpoint. As an example, `name.with/special@chars`
parameter value would be encoded as `name.with%2Fspecial%40chars`.

==== Retrieve Management Center License Expiration Time

This endpoint returns the expiration time in milliseconds (since epoch) of the license key assigned for the Management Center.
Returns `-1` if no license is assigned.

* *Request Type:* GET
* *URL:* `/rest/license`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/license
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "licenseExpirationTime": 4099755599515
}
```

=== Clusters Resource

This resource returns a list of clusters that are connected to the Management Center.

==== Retrieve Clusters

* *Request Type:* GET
* *URL:* `/rest/clusters`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["dev", "qa"]
```

=== Cluster Resource

This resource returns information related to the provided cluster name.

==== Retrieve Cluster Information

This endpoint returns address of the master node and the expiration time in milliseconds (since epoch) of the license
key assigned for the cluster. Returns `-1` for license expiration time if no license is assigned.

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "masterAddress": "192.168.2.78:5701",
  "licenseExpirationTime": 4099755599515
}
```

=== Members Resource

This resource returns a list of members belonging to the provided clusters.

==== Retrieve Members [GET] [/rest/clusters/{clustername}/members]

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
[
  "192.168.2.78:5701",
  "192.168.2.78:5702",
  "192.168.2.78:5703",
  "192.168.2.78:5704"
]
```

=== Member Resource

This resource returns information related to the provided member.

==== Retrieve Member Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "192.168.2.78:5701",
  "uuid": "11adba52-e19d-4407-a9e9-e0a271cef14a",
  "cpMemberUuid": "f5a8f8a4-f278-4a13-a23e-5accf5b02f42",
  "maxMemory": 129957888,
  "ownedPartitionCount": 68,
  "usedMemory": 60688784,
  "freeMemory": 24311408,
  "totalMemory": 85000192,
  "connectedClientCount": 1,
  "master": true
}
```

==== Retrieve Connection Manager Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/connectionManager`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701/connectionManager
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "clientConnectionCount": 2,
  "activeConnectionCount": 5,
  "connectionCount": 5
}
```

==== Retrieve Operation Service Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/operationService`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701/operationService
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "responseQueueSize": 0,
  "operationExecutorQueueSize": 0,
  "runningOperationsCount": 0,
  "remoteOperationCount": 1,
  "executedOperationCount": 461139,
  "operationThreadCount": 8
}
```

==== Retrieve Event Service Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/eventService`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701/eventService
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "eventThreadCount": 5,
  "eventQueueCapacity": 1000000,
  "eventQueueSize": 0
}
```

==== Retrieve Partition Service Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/partitionService`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701/partitionService
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "partitionCount": 271,
  "activePartitionCount": 68
}
```

==== Retrieve Proxy Service Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/proxyService`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701/proxyService
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "proxyCount": 8
}
```

==== Retrieve All Managed Executors

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/managedExecutors`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701/managedExecutors
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["hz:system", "hz:scheduled", "hz:client", "hz:query", "hz:io", "hz:async"]
```

==== Retrieve a Managed Executor

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/members/{member}/managedExecutors/{managedExecutor}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/members/192.168.2.78:5701
	  /managedExecutors/hz:system
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "name": "hz:system",
  "queueSize": 0,
  "poolSize": 0,
  "remainingQueueCapacity": 2147483647,
  "maximumPoolSize": 4,
  "completedTaskCount": 12,
  "terminated": false
}
```

=== Client Endpoints Resource

This resource returns a list of client endpoints belonging to the provided cluster. Please consider using the newly 
added <<client-statistics-resource, Client Statistics Resource>> 
as it contains more detailed information about clients.

==== Retrieve List of Client Endpoints

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/clients`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/clients
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["192.168.2.78:61708"]
```

==== Retrieve Client Endpoint Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/clients/{client}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/clients/192.168.2.78:61708
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "uuid": "6fae7af6-7a7c-4fa5-b165-cde24cf070f5",
  "address": "192.168.2.78:61708",
  "clientType": "JAVA",
  "name": "hz.client_1",
  "labels": [
    "label1"
  ]
}
```

=== Maps Resource

This resource returns a list of maps belonging to the provided cluster.


==== Retrieve List of Maps

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/maps`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/maps
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["customers", "orders"]
```

==== Retrieve Map Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/maps/{mapName}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/maps/customers
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "customers",
  "ownedEntryCount": 5085,
  "backupEntryCount": 5076,
  "ownedEntryMemoryCost": 833940,
  "backupEntryMemoryCost": 832464,
  "heapCost": 1666668,
  "lockedEntryCount": 2,
  "dirtyEntryCount": 0,
  "hits": 602,
  "lastAccessTime": 1532689094579,
  "lastUpdateTime": 1532689094576,
  "creationTime": 1532688789256,
  "putOperationCount": 5229,
  "getOperationCount": 2162,
  "removeOperationCount": 150,
  "otherOperationCount": 3687,
  "events": 10661,
  "maxPutLatency": 48,
  "maxGetLatency": 35,
  "maxRemoveLatency": 18034,
  "avgPutLatency": 0.5674125071715433,
  "avgGetLatency": 0.2479185938945421,
  "avgRemoveLatency": 5877.986666666667
}
```

=== MultiMaps Resource

This resource returns a list of multimaps belonging to the provided cluster.


==== Retrieve List of MultiMaps

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/multimaps`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/multimaps
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["customerAddresses"]
```

==== Retrieve MultiMap Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/multimaps/{multimapname}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/multimaps/customerAddresses
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "customerAddresses",
  "ownedEntryCount": 4862,
  "backupEntryCount": 4860,
  "ownedEntryMemoryCost": 0,
  "backupEntryMemoryCost": 0,
  "heapCost": 0,
  "lockedEntryCount": 1,
  "dirtyEntryCount": 0,
  "hits": 22,
  "lastAccessTime": 1532689253314,
  "lastUpdateTime": 1532689252591,
  "creationTime": 1532688790593,
  "putOperationCount": 5125,
  "getOperationCount": 931,
  "removeOperationCount": 216,
  "otherOperationCount": 373570,
  "events": 0,
  "maxPutLatency": 8,
  "maxGetLatency": 1,
  "maxRemoveLatency": 18001,
  "avgPutLatency": 0.3758048780487805,
  "avgGetLatency": 0.11170784103114931,
  "avgRemoveLatency": 1638.8472222222222
}
```

=== ReplicatedMaps Resource

This resource returns a list of replicated maps belonging to the provided cluster.


==== Retrieve List of ReplicatedMaps

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/replicatedmaps`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/replicatedmaps
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["replicated-map-1"]
```

==== Retrieve ReplicatedMap Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/replicatedmaps/{replicatedmapname}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/replicatedmaps/replicated-map-1
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "replicated-map-1",
  "ownedEntryCount": 10955,
  "ownedEntryMemoryCost": 394380,
  "hits": 15,
  "lastAccessTime": 1532689312581,
  "lastUpdateTime": 1532689312581,
  "creationTime": 1532688789493,
  "putOperationCount": 11561,
  "getOperationCount": 1051,
  "removeOperationCount": 522,
  "otherOperationCount": 355552,
  "events": 6024,
  "maxPutLatency": 1,
  "maxGetLatency": 1,
  "maxRemoveLatency": 1,
  "avgPutLatency": 0.006400830377994983,
  "avgGetLatency": 0.012369172216936251,
  "avgRemoveLatency": 0.011494252873563218
}
```


=== Queues Resource

This resource returns a list of queues belonging to the provided cluster.


==== Retrieve List of Queues

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/queues`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/queues
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["messages"]
```

==== Retrieve Queue Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/queues/{queueName}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/queues/messages
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "messages",
  "ownedItemCount": 55408,
  "backupItemCount": 55408,
  "minAge": 0,
  "maxAge": 0,
  "aveAge": 0,
  "numberOfOffers": 55408,
  "numberOfRejectedOffers": 0,
  "numberOfPolls": 0,
  "numberOfEmptyPolls": 0,
  "numberOfOtherOperations": 0,
  "numberOfEvents": 0,
  "creationTime": 1403602694196
}
```


=== Topics Resource

This resource returns a list of topics belonging to the provided cluster.


==== Retrieve List of Topics

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/topics`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/topics
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["news"]
```

==== Retrieve Topic Information

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/topics/{topicName}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/topics/news
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "news",
  "numberOfPublishes": 56370,
  "totalReceivedMessages": 56370,
  "creationTime": 1403602693411
}
```


=== Executors Resource

This resource returns a list of executors belonging to the provided cluster.

==== Retrieve List of Executors

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/executors`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/executors
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
["order-executor"]
```

==== Retrieve Executor Information [GET] [/rest/clusters/{clustername}/executors/{executorName}]

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/executors/{executorName}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/executors/order-executor
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "cluster": "dev",
  "name": "order-executor",
  "creationTime": 1403602694196,
  "pendingTaskCount": 0,
  "startedTaskCount": 1241,
  "completedTaskCount": 1241,
  "cancelledTaskCount": 0
}
```

[[client-statistics-resource]]
=== Client Statistics Resource

This resource returns a list of clients belonging to the provided cluster.


==== Retrieve List of Client UUIDs

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/clientStats`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/clientStats
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
[
  "f3b1e0e9-ea67-41b2-aba5-ea7480f02a93",
  "cebf4dc9-852c-4605-a181-ffe1cca371a4",
  "2371eed5-26e0-4470-92c1-41ea17110ef6",
  "139990b3-fbc0-43a8-9c12-be53913333f7",
  "d0364a1e-8665-46a8-af1d-be1af5580d07",
  "7f337f8a-3538-4b5c-8ffc-9d4ae459e956",
  "6ef9b6e5-5add-40d9-9319-ce502f55b5fc",
  "fead3a99-19de-431c-9dd0-d6ecc4a4b9c8",
  "e788e04e-2ded-4992-9d76-52c1973216e5",
  "654fc9fb-c5c1-48a0-9b69-0c129fce860f"
]
```

==== Retrieve Detailed Client Statistics [GET] [/rest/clusters/{clustername}/clientStats/{clientUuid}]

* *Request Type:* GET
* *URL:* `/rest/clusters/{clustername}/clientStats/{clientUuid}`
* *Request:*
+
```bash
curl http://localhost:8083/hazelcast-mancenter/rest/clusters/dev/clientStats/2371eed5-26e0-4470-92c1-41ea17110ef6
```
+
* *Response:* `200` (application/json)
* *Body:*
+
```json
{
  "type": "JAVA",
  "name": "hz.client_7",
  "address": "127.0.0.1:42733",
  "clusterConnectionTimestamp": 1507874427419,
  "enterprise": true,
  "lastStatisticsCollectionTime": 1507881309434,
  "osStats": {
    "committedVirtualMemorySize": 12976173056,
    "freePhysicalMemorySize": 3615662080,
    "freeSwapSpaceSize": 8447324160,
    "maxFileDescriptorCount": 1000000,
    "openFileDescriptorCount": 191,
    "processCpuTime": 252980000000,
    "systemLoadAverage": 83.0,
    "totalPhysicalMemorySize": 16756101120,
    "totalSwapSpaceSize": 8447324160
  },
  "runtimeStats": {
    "availableProcessors": 12,
    "freeMemory": 135665432,
    "maxMemory": 3724541952,
    "totalMemory": 361234432,
    "uptime": 6894992,
    "usedMemory": 225569000
  },
  "nearCacheStats": {
    "CACHE": {
      "a-cache": {
        "creationTime": 1507874429719,
        "evictions": 0,
        "hits": 0,
        "misses": 50,
        "ownedEntryCount": 0,
        "expirations": 0,
        "ownedEntryMemoryCost": 0,
        "lastPersistenceDuration": 0,
        "lastPersistenceKeyCount": 0,
        "lastPersistenceTime": 0,
        "lastPersistenceWrittenBytes": 0,
        "lastPersistenceFailure": ""
      },
      "b.cache": {
        "creationTime": 1507874429973,
        "evictions": 0,
        "hits": 0,
        "misses": 50,
        "ownedEntryCount": 0,
        "expirations": 0,
        "ownedEntryMemoryCost": 0,
        "lastPersistenceDuration": 0,
        "lastPersistenceKeyCount": 0,
        "lastPersistenceTime": 0,
        "lastPersistenceWrittenBytes": 0,
        "lastPersistenceFailure": ""
      }
    },
    "MAP": {
      "other,map": {
        "creationTime": 1507874428638,
        "evictions": 0,
        "hits": 100,
        "misses": 50,
        "ownedEntryCount": 0,
        "expirations": 0,
        "ownedEntryMemoryCost": 0,
        "lastPersistenceDuration": 0,
        "lastPersistenceKeyCount": 0,
        "lastPersistenceTime": 0,
        "lastPersistenceWrittenBytes": 0,
        "lastPersistenceFailure": ""
      },
      "employee-map": {
        "creationTime": 1507874427959,
        "evictions": 0,
        "hits": 100,
        "misses": 50,
        "ownedEntryCount": 0,
        "expirations": 0,
        "ownedEntryMemoryCost": 0,
        "lastPersistenceDuration": 0,
        "lastPersistenceKeyCount": 0,
        "lastPersistenceTime": 0,
        "lastPersistenceWrittenBytes": 0,
        "lastPersistenceFailure": ""
      }
    }
  },
  "userExecutorQueueSize": 0,
  "memberConnection": "ALL",
  "version": "UNKNOWN"
}
```
