
[[variable-replacers]]
== Variable Replacers

Variable replacers are used to replace custom strings during loading the configuration, either passed as command line
 arguments or as part of a configuration file, such as `ldap.properties` or `jaas.properties`. They can be used to mask
sensitive information such as usernames and passwords. Of course their usage is not limited to security related
information.

Variable replacers implement the interface `com.hazelcast.webmonitor.configreplacer.spi.ConfigReplacer` and they are
configured via the following command line arguments:

* `-Dhazelcast.mc.configReplacer.class`: Full class name of the replacer.
* `-Dhazelcast.mc.configReplacer.failIfValueMissing`: Specifies whether the loading configuration process stops when a
replacement value is missing. It is an optional attribute and its default value is true.
* Additional command line arguments specific to each replacer implementation. All of the properties for the built-in
replacers are explained in the upcoming sections.

The following replacer classes are provided by Hazelcast as example implementations of the `ConfigReplacer` interface.
Note that you can also implement your own replacers.

* `EncryptionReplacer`
* `PropertyReplacer`


Each example replacer is explained in the below sections.

=== EncryptionReplacer

This example `EncryptionReplacer` replaces encrypted variables by its plain form. The secret key for
encryption/decryption is generated from a password which can be a value in a file and/or environment specific values,
such as MAC address and actual user data.

Its full class name is `com.hazelcast.webmonitor.configreplacer.EncryptionReplacer` and the replacer prefix is `ENC`.
Here are the properties used to configure this example replacer:

* `hazelcast.mc.configReplacer.prop.cipherAlgorithm`: Cipher algorithm used for the encryption/decryption. Its default value is AES.
* `hazelcast.mc.configReplacer.prop.keyLengthBits`: Length (in bits) of the secret key to be generated. Its default value is 128.
* `hazelcast.mc.configReplacer.prop.passwordFile`: Path to a file whose content should be used as a part of the encryption password. When the property
is not provided no file is used as a part of the password. Its default value is null.
* `hazelcast.mc.configReplacer.prop.passwordNetworkInterface`: Name of network interface whose MAC address should be used as a part of the
encryption password. When the property is not provided no network interface property is used as a part of the password.
Its default value is null.
* `hazelcast.mc.configReplacer.prop.passwordUserProperties`: Specifies whether the current user properties (`user.name` and `user.home`) should be used
as a part of the encryption password. Its default value is true.
* `hazelcast.mc.configReplacer.prop.saltLengthBytes`: Length (in bytes) of a random password salt. Its default value is 8.
* `hazelcast.mc.configReplacer.prop.secretKeyAlgorithm`:  Name of the secret-key algorithm to be associated with the generated secret key. Its default
value is AES.
* `hazelcast.mc.configReplacer.prop.secretKeyFactoryAlgorithm`: Algorithm used to generate a secret key from a password. Its default value is
PBKDF2WithHmacSHA256.
* `hazelcast.mc.configReplacer.prop.securityProvider`: Name of a Java Security Provider to be used for retrieving the configured secret key factory and
the cipher. Its default value is null.

NOTE: Older Java versions may not support all the algorithms used as defaults. Please use the property values supported
your Java version.


As a usage example, let's create a password file and generate the encrypted strings out of this file.

1 -  Create the password file: `echo '/Za-uG3dDfpd,5.-' > /opt/master-password`

2 -  Define the encrypted variables:

[subs="attributes"]
```
java -cp {mc-war-file} \
    -Dhazelcast.mc.configReplacer.prop.passwordFile=/opt/master-password \
    -Dhazelcast.mc.configReplacer.prop.passwordUserProperties=false \
    com.hazelcast.webmonitor.configreplacer.EncryptionReplacer \
    "aPasswordToEncrypt" \

Output:

$ENC{wJxe1vfHTgg=:531:WkAEdSi//YWEbwvVNoU9mUyZ0DE49acJeaJmGalHHfA=}
```

3 - Configure the replacer and provide the encrypted variables as command line arguments while starting Management Center:

[subs="attributes"]
```
java \
    -Dhazelcast.mc.configReplacer.class=com.hazelcast.webmonitor.configreplacer.EncryptionReplacer \
    -Dhazelcast.mc.configReplacer.prop.passwordFile=/opt/master-password \
    -Dhazelcast.mc.configReplacer.prop.passwordUserProperties=false \
    -Dhazelcast.mc.tls.enabled=true \
    -Dhazelcast.mc.tls.keyStore=/opt/mancenter.keystore \
    -Dhazelcast.mc.tls.keyStorePassword='$ENC{wJxe1vfHTgg=:531:WkAEdSi//YWEbwvVNoU9mUyZ0DE49acJeaJmGalHHfA=}' \
    -jar {mc-war-file}
```

=== PropertyReplacer

The `PropertyReplacer` replaces variables by properties with the given name. Usually the system properties are used,
e.g., `${user.name}`.

Its full class name is `com.hazelcast.webmonitor.configreplacer.PropertyReplacer` and the replacer prefix is empty string ("").


=== Implementing Custom Replacers

You can also provide your own replacer implementations. All replacers have to implement the three methods that have
 the same signatures as the methods of the following interface:

```
import java.util.Properties;

public interface ConfigReplacer {
    void init(Properties properties);
    String getPrefix();
    String getReplacement(String maskedValue);
}
```
