
[[deploying-and-starting]]
== Getting Started

To start using Management Center:

. download the Hazelcast IMDG or Management Center package
. start the Management Center service
. launch the Management Center user interface.

=== Downloading Management Center

Hazelcast Management Center is included in the Hazelcast IMDG download package.
You can download it from the https://hazelcast.org/download/#imdg[download page]
of Hazelcast's website.

When a new Hazelcast IMDG version is released, it comes with the Management Center
having the same version with IMDG.
There may be times when a new Management Center version is released before a new
version of Hazelcast IMDG. In that case, you may download the new Management Center
from its https://hazelcast.org/download/#management-center[download page] as a
separate package. Note that, Management Center is compatible with
Hazelcast IMDG cluster members having the same or the previous minor version.
For example, Hazelcast Management Center version 3.12.x works with Hazelcast IMDG
cluster members having version 3.11.x or 3.12.x.

=== Starting the Management Center Service

You have two options to start the Management Center service:

* deploying the file `{mc-war-file}` on your Java application server/container
* starting Hazelcast Management Center from the command line
* using the scripts that come with the download package.

NOTE: Starting with version 3.10, you need Java Runtime Environment 1.8 or
later to run Hazelcast Management Center.

[[starting-with-war-file]]
==== Using the Command Line

After you downloaded, extract the Hazelcast IMDG or Management Center package.
The extracted directory, i.e., `hazelcast-management-center-{mancenter-version}`,
contains the `{mc-war-file}` file.

You can start this file directly from the command line using the following command:

[subs="attributes"]
```
java -jar {mc-war-file} 8080 hazelcast-mancenter
```

The above command starts the  Hazelcast Management Center service on
the port `8080` with the `hazelcast-mancenter` context
path (`\http://localhost:8080/hazelcast-mancenter`). Note that,
the Hazelcast IMDG cluster members should know the
URL of the `hazelcast-mancenter` application before they start.
See the <<connecting-hazelcast-members-to-management-center,
Connecting IMDG Members to Management Center chapter>>.

For the options you can provide when starting with the
command line, see the <<configuring-management-center,
Configuring Management Center chapter>>. In that chapter,
you can learn about topics including how to start with a
license or extra classpath, how to configure the security,
disk usage, update interval or logging.

[[deploying-to-application-server]]
==== Deploying to Application Server

Instead of starting at the command line, you can
deploy Management Center to your application server (Tomcat, Jetty, etc.).

If you have deployed `{mc-war-file}` in your already-SSL-enabled web
container, configure `hazelcast.xml` as follows, before starting
a Hazelcast IMDG cluster member:

[source,xml]
----
<management-center enabled="true">
    https://localhost:sslPortNumber/hazelcast-mancenter
</management-center>
----

If you are using an untrusted certificate for your container,
which you created yourself, you need to add that certificate
to your JVM first. Download the certificate from the browser
and add it to the JVM as follows:

```
keytool -import -noprompt -trustcacerts -alias <AliasName> -file <certificateFile> -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass <Password>
```

[[starting-with-scripts]]
==== Using Scripts in the Package

As another option, you can use the `start.bat` or `start.sh` scripts,
which come with the download package, to start the Management Center.
You can find these scripts under the extracted directory. 
