include::attributes.adoc[]
= Hazelcast Management Center Reference Manual
Version {mancenter-version}
:icons: font
:idprefix:
:idseparator: -
:imagesdir: images
:safe-mode: SECURE
:sectanchors:
:sectlinks:
:source-highlighter: coderay
:source-indent: 0
:source-language: java
:stylesheet: stylesheets/hazelcast.css
:toc: left
:toclevels: 4
:toc-title: Table of Contents
:docinfo: shared


Welcome to the Reference Manual of Hazelcast
IMDG Management Center. This document provides
information on the usage of the Management Center.

Hazelcast Management Center enables you to monitor
and manage your cluster members running Hazelcast IMDG.
In addition to monitoring the overall state of your
clusters, you can also analyze and browse your data
structures in detail, update map configurations and
take thread dumps from the members. You can run scripts
(JavaScript, Groovy, etc.) and commands on your members
with its scripting and console modules.

See the https://docs.hazelcast.org/docs/latest/manual/html-single/[Hazelcast IMDG Reference Manual] for all Hazelcast
IMDG topics including the clusters and their operations,
clients, data structures, computing and WAN replication.

:numbered:

include::browser_compatibility.adoc[]

include::downloading_starting.adoc[]

include::configuring.adoc[]

include::connecting_members.adoc[]

include::launching_ui.adoc[]

include::authentication_options.adoc[]

include::user_interface.adoc[]

include::status_page.adoc[]

include::monitoring_members.adoc[]

include::monitoring_clients.adoc[]

include::monitoring_data_structures.adoc[]

include::monitoring_wan_replication.adoc[]

include::scripting.adoc[]

include::console.adoc[]

include::alerts.adoc[]

include::administer.adoc[]

include::license_screen.adoc[]

include::time_travel.adoc[]

include::clustered_rest.adoc[]

include::clustered_jmx.adoc[]

include::mc_conf_tool.adoc[]

include::documentation.adoc[]

include::heap_size.adoc[]

include::migration_guides.adoc[]


