[[preface]]
== Preface

Hazelcast Management Center enables you to monitor
and manage your cluster members running Hazelcast IMDG.
In addition to monitoring the overall state of your
clusters, you can also analyze and browse your data
structures in detail, update map configurations and
take thread dumps from the members. You can run scripts
(JavaScript, Groovy, etc.) and commands on your members
with its scripting and console modules.

[[naming]]
=== Naming

* *Hazelcast Management Center* or *Management Center* refers to
the Hazelcast IMDG cluster monitoring tool provided by Hazelcast, Inc.
* *Hazelcast IMDG* or just *Hazelcast* refers to the Hazelcast in-memory
data grid middleware. *Hazelcast* is also the name of the company
(Hazelcast, Inc.) providing Hazelcast IMDG.

=== Hazelcast IMDG

Hazelcast Management Center is delivered with Hazelcast IMDG. It can
also be downloaded as a separate package from the
https://hazelcast.org/download/#management-center[hazelcast.org] website.

See the https://docs.hazelcast.org/docs/latest/manual/html-single/[Hazelcast IMDG Reference Manual]
for all Hazelcast IMDG topics including the clusters and their operations,
clients, data structures, computing and WAN replication.

[[licensing]]
=== Licensing

This Reference Manual is free and provided under the Apache License, Version 2.0.

Hazelcast Management Center requires either a Management Center license or Hazelcast IMDG Enterprise license or Hazelcast IMDG Enterprise HD license. It also has a free version which lets you to monitor your cluster having up to three IMDG members.

[[trademarks]]
=== Trademarks

Hazelcast is a registered trademark of Hazelcast, Inc. All other
trademarks in this manual are held by their respective owners.

[[getting-help]]
=== Getting Help

Support is provided via the following channels:

* https://stackoverflow.com/questions/tagged/hazelcast[Stack Overflow]
(ask a question on how to use Management Center properly and troubleshoot your setup)
* https://groups.google.com/forum/#!forum/hazelcast[Hazelcast mailing list]
(propose features and discuss your ideas with the team)

=== Release Notes

See the https://docs.hazelcast.org/docs/management-center/rn/index.html[Release Notes] document
for the new features, enhancements and fixes performed for each Hazelcast Management Center release.