

[[using-management-center-with-tlsssl-only]]
== Using Management Center with TLS/SSL Only

To encrypt data transmitted over all channels of Management Center using TLS/SSL, make sure you do all of the following:

* Deploy Management Center on a TLS/SSL enabled container or start it from the command line with TLS/SSL enabled. See <<deploying-and-starting, Installing Management Center>>.
** Another option is to place Management Center behind a TLS-enabled reverse proxy. In that case, make sure your reverse proxy sets the necessary HTTP header (`X-Forwarded-Proto`) for resolving the correct protocol.
* Enable TLS/SSL communication to Management Center for your Hazelcast cluster. See <<connecting-hazelcast-members-to-management-center, Connecting Hazelcast members to Management Center>>.
* If you're using Clustered JMX on Management center, enable TLS/SSL for it. See <<clustered-jmx-via-management-center, Enabling TLS/SSL for Clustered JMX>>.
* If you're using LDAP authentication, make sure you use LDAPS or enable the "Start TLS" field. See <<ldap-authentication, LDAP Authentication>>.
