= Connecting to the Clusters
[[connecting-hazelcast-members-to-management-center]]

After you start and/or configure the Management Center service
as explained in the xref:getting-started.adoc#starting-the-management-center-service[Starting the Management Center Service] and
xref:configuring.adoc[Configuring the Management Center] chapters, make sure that
`\http://localhost:8080` is up.

To connect the Management Center to your clusters, you have two options
to be performed in Management Center:

1. You can provide the IP addresses or hostnames of one or more Hazelcast members.
2. Or, you can upload a configuration file in XML or YAML format.
Management Center starts a client for each of the Hazelcast clusters. This configuration file
is for that Management Center client. See xref:managing-clusters.adoc#creating-a-cluster-configuration-by-uploading-file[here] for details on this configuration file.
You can think of Management Center as a client connecting to the Hazelcast clusters.

If you enabled TLS/SSL on a Hazelcast cluster, then you need to perform the 2.
step listed above, i.e., upload a configuration file. This configuration file needs
to contain the parameters same as the ones you provide in the case when a client
connects to a TLS/SSL enabled Hazelcast cluster. See xref:{page-latest-supported-hazelcast}@hazelcast:security:tls-ssl.adoc[here] for details on TLS/SSL configurations.

NOTE: When connecting to multiple clusters from the same Management Center, please ensure that the
cluster names are unique.  Management Center does not support simultaneous connections to more than
one cluster with the same cluster name.

NOTE: If the cluster uses
xref:{page-latest-supported-hazelcast}@hazelcast:clusters:network-configuration.adoc[Advanced Network],
then the provided member address should be the client address of the member.


== Configuring Security on the Members

NOTE: This section applies only to IMDG 4.2 and newer (including Hazelcast 5.x). If you use an older version, you can skip this configuration step.

If `security` is enabled in the member configurations, then the `management-permission` should be granted for the Management Center client. Also, in this case the client should authenticate itself, which means you need to set up the connection by uploading a configuration XMl (or YAML): see xref:ROOT:managing-clusters.adoc#creating-a-cluster-configuration-by-uploading-file[here].

An example member configuration is shown below:

```xml
<hazelcast xmlns="http://www.hazelcast.com/schema/config">
    <security enabled="true">
        <realms>
            <realm name="client-realm">
                <authentication>
                    ...
                </authentication>
            </realm>
        </realms>
        <client-authentication realm="client-realm" />
        <client-permissions>
            <management-permission principal="mcadmin" />
        </client-permissions>
    </security>
</hazelcast>

```

An example client configuration is shown below:

```xml
<hazelcast-client xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                  http://www.hazelcast.com/schema/client-config/hazelcast-client-config-4.2.xsd">
    <cluster-name>dev</cluster-name>

    <security>
        <username-password username="mcadmin" password="mypassword"/>
    </security>
</hazelcast-client>
```
