= Hazelcast Management Center {full-version}
[[preface]]

Welcome to the Hazelcast Management Center.
This manual includes concepts and instructions
to guide you on how to use Management Center to
monitor your Hazelcast clusters.
You can also find links to relevant sections of this documentation in the Management Center.

[[naming]]
== Naming

* *Hazelcast Management Center* or *Management Center* refers to
the Hazelcast cluster monitoring tool provided by Hazelcast, Inc.
* *Hazelcast* refers to the Hazelcast in-memory
data grid and batch/stream processing software. *Hazelcast* is also the name of the company
(Hazelcast, Inc.).

== Hazelcast

Hazelcast Management Center is delivered with Hazelcast. It can
also be downloaded as a separate package from the
link:https://hazelcast.com/open-source-projects/downloads/#hazelcast-management-center[hazelcast.com website].

See the xref:{page-latest-supported-hazelcast}@hazelcast:getting-started:quickstart.adoc[Hazelcast documentation]
for all Hazelcast topics including deploying and managing clusters,
clients, data structures, computing, and WAN replication.

[[licensing]]
== Licensing

All documentation is available under the terms of a link:https://creativecommons.org/licenses/by-nc-sa/3.0/[Creative Commons License].

You can monitor a cluster with up to three members for free.

To monitor larger clusters, you need a Hazelcast Enterprise license.

[[trademarks]]
== Trademarks

Hazelcast is a registered trademark of Hazelcast, Inc. All other
trademarks in the documentation are held by their respective owners.

[[getting-help]]
== Getting Help

Support is provided via the following channels:

* xref:troubleshooting.adoc[Troubleshooting page] of this guide
* https://stackoverflow.com/questions/tagged/hazelcast[Stack Overflow]
(ask a question about how to use Management Center properly and troubleshoot your setup)
* https://groups.google.com/forum/#!forum/hazelcast[Hazelcast mailing list]
(propose features and discuss your ideas with the team)
* https://slack.hazelcast.com/[Hazelcast community Slack]
(discuss anything related to Hazelcast and Management Center with other
Hazelcast users and Hazelcast developers)

== Release Notes

See the https://docs.hazelcast.org/docs/management-center/rn/index.html[Release Notes] document
for the new features, enhancements and fixes performed for each Hazelcast Management Center release.

