= Hazelcast Management Center Reference Manual {page-component-display-version}
[[preface]]
Welcome to the Hazelcast Management Center Reference Manual.
This manual includes concepts and instructions
to guide you on how to use Management Center to
monitor your Hazelcast IMDG and Jet Clusters.

[[naming]]
== Naming

* *Hazelcast Management Center* or *Management Center* refers to
the Hazelcast IMDG and Jet cluster monitoring tool provided by Hazelcast, Inc.
* *Hazelcast IMDG* or just *Hazelcast* refers to the Hazelcast in-memory
data grid middleware. *Hazelcast* is also the name of the company
(Hazelcast, Inc.) providing Hazelcast IMDG and Hazelcast Jet.
* *Hazelcast Jet* or *Jet* refers to the distributed data
processing engine provided by Hazelcast, Inc.

== Hazelcast IMDG

Hazelcast Management Center is delivered with Hazelcast IMDG. It can
also be downloaded as a separate package from the
https://hazelcast.org/download/#management-center[hazelcast.org] website.

See the https://docs.hazelcast.org/docs/latest/manual/html-single/[Hazelcast IMDG Reference Manual]
for all Hazelcast IMDG topics including the clusters and their operations,
clients, data structures, computing and WAN replication.

[[licensing]]
== Licensing

This Reference Manual is free and provided
under the Apache License, Version 2.0.

Hazelcast Management Center requires either of the following:

* Management Center license
* Hazelcast IMDG Enterprise license
* Hazelcast IMDG Enterprise HD license
* Hazelcast Jet Enterprise license

It also has a free version which lets you to monitor your clusters having up to three
IMDG and Jet members each.

[[trademarks]]
== Trademarks

Hazelcast is a registered trademark of Hazelcast, Inc. All other
trademarks in this manual are held by their respective owners.

[[getting-help]]
== Getting Help

Support is provided via the following channels:

* xref:troubleshooting.adoc[Troubleshooting chapter] of this guide
* https://stackoverflow.com/questions/tagged/hazelcast[Stack Overflow]
(ask a question on how to use Management Center properly and troubleshoot your setup)
* https://groups.google.com/forum/#!forum/hazelcast[Hazelcast mailing list]
(propose features and discuss your ideas with the team)
* https://slack.hazelcast.com/[Hazelcast Community Slack]
(discuss anything related to Hazelcast IMDG, Jet and Management Center with other
Hazelcast users and Hazelcast developers)

== Release Notes

See the https://docs.hazelcast.org/docs/management-center/rn/index.html[Release Notes] document
for the new features, enhancements and fixes performed for each Hazelcast Management Center release.

