= Upgrading from previous versions
[[migration-guides]]

== Upgrading to Management Center 5.x

=== Changes in 5.1.x

 * The `mc-conf.sh` command was renamed to `hz-mc conf`
 * The `start.sh` was deprecated and is superseded by the `hz-mc start` command
 * The supported way for starting up a standalone Management Center instance was changed from `java -jar ...` command to `hz-mc start`

== Upgrading to Management Center 4.x

This section lists the changes for you to be aware when you have been using Management Center 3.x versions and want to use 5.x or newer ones.

=== Changes in 3.12.x

* Default home directory location has been changed from `<user-home>/hazelcast-mancenter-<version>` to `<user-home>/hazelcast-mc`.
* Parameter to change home directory location has been changed from `hazelcast.mancenter.home` to `hazelcast.mc.home`.
* The `UpdateLdapPassword` utility (available via `updateLdapPassword.sh` or `updateLdapPassword.bat` scripts) has been merged into the MC Conf tool (available via the `hz-mc conf` or `mc-conf.bat` scripts).

=== Changes in 3.10.x

* Hazelcast Management Center’s default URL has been changed from `localhost:8080/mancenter` to `localhost:8080/hazelcast-mancenter`.
* Default home directory location has been changed from `<user-home>/mancenter-<version>` to `<user-home>/hazelcast-mancenter-<version>`.
* Name of the WAR file has been changed from `mancenter-\{version}.war` to `hazelcast-mancenter-\{version}.war`.

=== Changes in 3.8.x

Starting with Management Center 3.8.4, you can
use the following system properties for Clustered JMX
via Management Center:

* `-Dhazelcast.mc.jmx.rmi.port=9001`
* `-Dhazelcast.mc.jmx.host=localhost`

See the xref:integrate:jmx.adoc[Clustered JMX via Management Center section].
