= Migration Guides

This appendix provides information on compatibility related changes for Hazelcast Management Center releases.

== Hazelcast Management Center 3.12.x

* Default home directory location has been changed from `<user-home>/hazelcast-mancenter-<version>` to `<user-home>/hazelcast-mc`.
* Parameter to change home directory location has been changed from `hazelcast.mancenter.home` to `hazelcast.mc.home`.
* The `UpdateLdapPassword` utility (available via `updateLdapPassword.sh` or `updateLdapPassword.bat` scripts) has been merged into the MC Conf tool (available via the `mc-conf.sh` or `mc-conf.bat` scripts).

== Hazelcast Management Center 3.10.x

* Hazelcast Management Center’s default URL has been changed from `localhost:8080/mancenter` to `localhost:8080/hazelcast-mancenter`.
* Default home directory location has been changed from `<user-home>/mancenter-<version>` to `<user-home>/hazelcast-mancenter-<version>`.
* Name of the WAR file has been changed from `mancenter-\{version}.war` to `hazelcast-mancenter-\{version}.war`.

== Hazelcast Management Center 3.8.x

Starting with Management Center 3.8.4, you can
use the following system properties for Clustered JMX
via Management Center:

* `-Dhazelcast.mc.jmx.rmi.port=9001`
* `-Dhazelcast.mc.jmx.host=localhost`

See the xref:integrate:jmx.adoc[Clustered JMX via Management Center chapter].
