
= What's new in Management Center 5.7
:description: Here are the highlights of what’s new and improved in Hazelcast Management Center 5.7, including Prometheus Exporter updates, FIPS-compliance and CP Subsystem improvements.

{description}

IMPORTANT: Hazelcast Management Center 5.7 requires Java 17 or later.

== Metrics updates for Prometheus Exporter
Management Center's Prometheus Exporter now follows best practice for metric formats while preserving backward compatibility. The new format metrics are available for lists, sets, and maps. For more information, see xref:integrate:prometheus-metrics.adoc[].

== CP Subsystem improvements

We've improved the CP Subsystem screen to provide clearer visibility into the CP state, with better tracking of CP Group leadership and the introduction of a last-seen timestamp. Identification of CP promotion candidates has also been improved by excluding Lite members from promotion. 

== FIPS-compliant with BouncyCastle update

Management Center now supports FIPS-compliant mode with an updated BouncyCastle implementation.

== General design and UI improvements
UI design improvements for better readability around cards, typography, and table spacing.

TIP: Most of these improvements were requested by the Hazelcast Product Strategy Board. To find out more or discuss joining, see https://hazelcast.com/lp/product-strategy-board/?utm_source=docs-website[Product Strategy Board].

== Release notes
For a full list of bug fixes and enhancements, see xref:release-notes:releases.adoc[].

To get started with Hazelcast Management Center, or upgrade an existing installation, see xref:getting-started:install.adoc[].

NOTE: For new and improved features in Hazelcast Platform 5.5, see xref:{page-latest-supported-hazelcast}@hazelcast:ROOT:whats-new.adoc[What's new in Hazelcast Platform 5.5].