= 5.0 Release Notes
:description: These release notes list any new features, enhancements, and fixes that were made between version 4.x and 5.0 of Hazelcast Management Center.

{description}

== New Features

* User Interface Redesign: Management Center has a completely redesigned interface for a better and more consistent user experience. 
* In addition to the simplified and improved overall usage functionalities, the user experience around WAN Replication/Sync and Client Filtering pages have been redesigned.
* DML Support for SQL Browser: It is now possible to use SQL DML statements such as CREATE MAPPING, INSERT INTO and SINK INTO in the SQL Browser.
* Secure Clustered REST API Endpoints: Clustered REST API now requires authentication. [MC-825]
* Command line tool mc-conf manages the tokens for the Clustered REST API Endpoints. [MC-822]
* Clustered REST API Endpoint for Client Filtering: You can use the new API endpoints for client filtering to automate
the process of filtering clients of a cluster. [MC-630]
* Secure Prometheus Exporter: You can configure the Prometheus exporter to require authentication now. [MC-772]

== Enhancements

* Introduced automatic run of a Config Healthcheck when cluster topology or effective configuration of member changes [MC-674]
* Improved the integration with Hazelcast Cloud; Management Center user interface now hides elements that are not usable on Hazelcat Cloud. [MC-613]
* Optimized metrics storage for writes. [MC-803]
* Management Center now shows periodic diagnostics information about the metrics storage. [MC-257]
* Added inconsistent Jet config detection to Config Healthcheck. [MC-999]
* Added support for using Active Directory over TLS. [MC-960]
* Distributed map entries that are generic records serialized via compact serialization can now be viewed via Map Browser. [MC-959]
* Added environment variables to specify a target cluster when starting Management Center via Docker. [MC-913]
* Added a command line option to specify the hostname representing the interface to which the embedded Jetty instance will bind. [MC-897]
* Added an option to output as JSON to the mc-conf command for creating tokens. [MC-898]
* Hazelcast license feature names have been updated to reflect the current features that Hazelcast offers in its enterprise edition.
* All Hazelcast license features are now shown on the Cluster License page. [MC-853]
* Improved the wording for the warning message about recommended number of available processors. [MC-929]

== Fixes

* No connection failure message is shown when connecting to a new cluster successfully. [MC-793]
* Rolling Upgrade screen now shows the next version of Hazelcast as 5.0. [MC-893]
* Inaccurate warning message about cluster having members not included in the config are no longer shown in the Edit Cluster Config dialog. [MC-912]
* Cluster Type is replaced with a "Supports Streaming" flag. [MC-908]
* Connecting to a cluster that has advanced network configured now works correctly. [MC-860]
* Memory is no longer shown as 0 when a map is configured with OBJECT in-memory format. [MC-341]
* Invalid maximum size policies are removed from the map configuration screen and missing ones are added. [MC-545]
* Cache names having special characters are handled correctly now. [MC-217]

== Notes

* Management Center 5.0 does not support Jet 4.5. It only supports IMDG 4.2, Hazelcast Platform 5.0 and later.
* Management Center 5.0 supports SQL Browsing on Hazelcast Platform 5.0 and later.
* You should avoid updating the client filtering configuration during the rolling upgrade if multiple Management Center
instances are connected to the same cluster to keep the configuration consistent.
* Prometheus exporter is now a licensed feature.