= 5.3.2 Release Notes
:description: These release notes list any new features, enhancements, and fixes that were made between version 5.3.1 and 5.3.2 of Hazelcast Management Center (MC).

{description}

[[enh-532]]
== Enhancements

* **SQL Browser:**
** Added an ability to see a query from Query history without execution. [MC-2091]
** Updated texts in Data Explorer. [MC-2224]
* Now a banner is displayed when repartitioning is in progress. [MC-2132]
* Improved database error messages. [MC-2063]
* Jetty SNI check is disabled by default. [MC-2276]


[[fixes-532]]
== Fixes

* **SQL Browser:**
** Fixed primary key violation on a simultaneous executions of multiple queries. [MC-2050]
* Fixed incorrect Jet metrics during the first minute after MC is connected. [MC-1578]
* Fixed false positive HeathCheck warnings for maps created from a default config. [MC-2226]
* MC no longer blocks HTTP calls when a member config is not available. [MC-2250] [MC-2259]
* MC no longer suppresses authentication error messages when Local Security Provider is used. [MC-2232]
* MC no longer throws an exception when deleting a misconfigured cluster connection. [MC-2237]
* MC no longer throws an exception when WAN publisher name is not set. [MC-2249]