= 5.3.2 Release Notes
:description: These release notes list any new features, enhancements, and fixes that were made between version 5.3.1 and 5.3.2 of Hazelcast Management Center (MC).

{description}

[[enh-532]]
== Enhancements

* **SQL Browser:**
** Added an ability to see a query from Query history without execution. [MC-2091]
** Updated UI text on the welcome screen of the Data Explorer. [MC-2224]
* A banner is now displayed when repartitioning is in progress. [MC-2132]
* Improved database error messages. [MC-2063]
* Jetty SNI host check is now disabled by default. [MC-2276]


[[fixes-532]]
== Fixes

* **SQL Browser:**
** Fixed a primary key violation that occurred when executing multiple simultaneous queries. [MC-2050]
* Fixed incorrect Jet metrics that were displayed one minute after connecting to MC. [MC-1578]
* Fixed false positive HealthCheck warnings for maps created using the default configuration. [MC-2226]
* MC no longer blocks HTTP calls when a member configuration is unavailable. [MC-2250] [MC-2259]
* MC no longer suppresses authentication error messages when Local Security Provider is used. [MC-2232]
* MC no longer throws an exception when deleting a misconfigured cluster connection. [MC-2237]
* MC no longer throws an exception when the WAN publisher name is not set. [MC-2249]