= 5.4.0-BETA-2 Release Notes
:description:
These release notes list any new features, enhancements, and fixes that were made between version 5.3.3 and 5.4.0-BETA-2 of Hazelcast Management Center (MC).
{description}

NOTE: Hazelcast Management Center 5.4 requires Java 17 or later to run.

NOTE: This only applies if you are upgrading your MC: MC 5.4.0 uses H2 2.x as its internal database instead of H2 1.x used by the previous MC releases. 
H2 1.x and 2.x are not compatible so a data migration step is required.
If you use the provided `hz-mc` or `mc-start` scripts to start MC, no further actions are needed as they handle the migration seamlessly. If you use
a custom run script, refer to the documentation for comprehensive instructions on migrating MC data. If the internal database is not upgraded, then MC will start with a new configuration.

== New Features

* **HealthCheck**
** Introduced semantic identifiers for the checks. [MC-2402]
** Added an ability to see all the suppressed checks. [MC-1750]
** Added an ability to unsuppress checks. [MC-1749]
** Added an ability to search and filter HealthCheck results. [MC-2445]
** Added HealthCheck status info to Dashboard. [MC-2437]
** Added an ability to disable a check for specific data structures. [MC-2424]
** Added a check for `eviction-policy` and `eviction-size` consistency. [MC-2426]
** Added a check for CP Subsystem running in Unsafe mode. [MC-2364]
** Added a check for a map backup count set to 0. [MC-2350]
** Added a check for an even cluster size. [MC-2322]
** Added a check for CPMap configuration. [MC-2519]
** Added a check for a soft limit of CPMap instances. [MC-2505]
** Added a check for members TPC configuration. [MC-2204]
** Added checks for Tiered Storage configuration. [MC-2550]
** Added HealthCheck counters to Prometheus Exporter. [MC-2439]
* Added an ability to terminate CP sessions. [MC-1719]
* Added support for CPMap data structure. [MC-2462]
* Added an ability to pause and resume streaming output in SQL Browser. [MC-2236]
* Added Favourites menu to the left panel. [MC-973]
* Added a promo page for all licensed features. [MC-1038]

== Enhancements

* **Console access**
** The Hazelcast Command-Line Client (CLC) has replaced the MC Console. CLC uses the same member config option to enable or disable the capability. [MC-2189]
* **SQL Browser**
** Added an automatic SQL formatter to SQL Browser. [MC-2351]
** Added a proper error message to SQL Browser when Jet is disabled. [MC-2410]
** Added a proper error message to SQL Browser when  a mapping cannot be generated for an empty map. [MC-2270]
** All maps are now shown in Connector Wizard instead of just the unmapped ones. [MC-2247]
** Made View icon blue instead of red to avoid confusion. [MC-2201]
** Added an option to load the query from the query history into SQL Editor tab without executing it. [MC-2179]
** Only expression at the cursor is executed. [MC-1957]
* **CP Subsystem**
** Added support for CP Subsystem in Unsafe mode. [MC-2121]
** CP members priority is now displayed. [MC-1662]
** CP member status is now dynamically updated. [MC-2478]
** Only CP members are now shown on CP Dashboards. [MC-2517]
** MC is now resilient to CP member deletion. [MC-1499]
* Added caching of static resources. [MC-2571]
* Added negative values support to Map Browser. [MC-2555]
* Added Tiered Storage parameters to Map Config screen. [MC-1829]
* Improved Tiered Storage charts. [MC-2549]
* Native memory size format in HealthCheck is now reported in human-readable format instead of bytes. [MC-2569]
* Added protection to `buildInfo` endpoint. [MC-2461]
* Added logging of user IP address to Audit logs. [MC-2365]
* Rebranded MC to a new Hazelcast company style. [MC-2170]
* Added persistence information to Caches and Maps tables. [MC-2243]
* Added useful links to the left panel. [MC-2274]
* Added a banner to notify about a repartitioning in progress. [MC-2132]
* Added a warning member addresses contain `localhost` in MC running in Docker. [MC-2018]
* Added a marking for members with TPC enabled in Members table. [MC-2171]
* Added member's Startup Time to Members table. [MC-1138]
* Improved `Node limit exceeded` banner. [MC-2481]
* Improved MC resiliency in case of a cluster producing huge amount of metrics. [MC-2376]
* Upgraded H2 1.x to H2 2.x. [MC-2283]
* Made timestamps optional in Prometheus Exporter. [MC-2127]
* Improved displaying of small values to `< 0.01` instead of `0`. [MC-2448]

== Fixes

* MC no longer displays warning about missing packages on startup. [MC-2558]
* MC no longer throws an exception when Jet is disabled. [MC-2289]
* MC no longer throws an exception when on Streaming page and 4.x cluster. [MC-2531]
* MC no longer logs exceptions on a cluster delete operation. [MC-1177]
* MC no longer show JMX cluster beans for 2 minutes after cluster disconnection. [MC-2602]
* MC no longer tries to connect to websocket while the app is not initialized. [MC-2560]
* MC no longer allows to press `Promote` button when member is being promoted. [MC-2490]
* MC no longer allows to press `Upgrade` button after a successful rolling upgrade. [MC-2423]
* MC no longer sporadically goes a listing page instead of particular data structure. [MC-1971]
* MC no longer throws `Multiple metrics found for metric` exception. [MC-1968]
* MC no longer shows incorrect Jet job metrics for the first minute after connection. [MC-1968]
* Fixed an error on startup on Windows with Turkish locale. [MC-2554]
* Fixed an error on Persistence page when node limit is exceeded. [MC-2514]
* Fixed Map Journal enablement representation. [MC-2420]
* Fixed incorrect docs link in `hz-mc --help`. [MC-2401]
* Fixed Map Sink vertex stats on Job page. [MC-2319]
* MC no longer needs a master member state for operations. [MC-2467]
