= Troubleshoot Management Center
:page-aliases: ROOT:automated-security-scan.adoc, ROOT:troubleshooting.adoc, ROOT:ui-logs.adoc

This topic describes how to deal with known issues and also how to read the user interface logs of Management Center.

== Horizontal scrollbar in tables when using Mac

Mac automatically shows a horizontal scrollbar in the status tables of Management Center, when you scroll through a table content.

The scrollbar should hide shortly after you stop scrolling. This is the default behavior and it shouldn't
cause any inconvenience. However, if you still want to change it, see the "Show scroll bars" section of the
link:https://support.apple.com/guide/mac-help/change-general-preferences-mchlp1225/mac["Change General preferences on Mac" guide].

== Experience timeout

If you experience a timeout when running scripts or SQL queries, you can increase the timeout value
in the xref:deploy-manage:system-properties.adoc#hazelcast-mc-cluster-operation-timeout[`hazelcast.mc.cluster.operation.timeout.millis`] property.

== Cannot open the configuration for a data structure

If a data structure name contains special characters, Management Center may not be able to display its configuration.

We recommend that you restrict names to letters, digits, and the `-`, `_`, and `.` characters. For more information, see xref:hazelcast:data-structures:distributed-data-structures.adoc#naming-data-structures[Naming Data Structures].
