= Trigger a force-start
:description: You can trigger a force-start to force a cluster with persistence enabled to restart and delete its persistence store when one or more members are missing after a cluster-wide restart.
:page-enterprise: true

{description}

A cluster whose recovery policy is set to `FULL_RECOVERY_ONLY` can recover after a cluster-wide restart only if all members restart with a valid partition table.

If a member is missing after a cluster-wide restart or if the member's partition table is invalid, the cluster cannot restart unless all members first delete their persistence stores.

A force-start deletes the persistence stores of all members in the cluster and then restarts the cluster.

== Before you begin

Go to *Administration* > *Persistence* and check the *Cluster Status* field. Only trigger a force-start if the cluster status is *In_Progress*, which means your cluster is missing a member.

To learn more about persistence in Hazelcast and what happens after a cluster-wide restart, see xref:{page-latest-supported-hazelcast}@hazelcast:storage:recover-single-member.adoc#what-happens-when-the-whole-cluster-restarts[What Happens When the Whole Cluster Restarts] in the Platform documentation.

This page is available only to admin users.

== Trigger a force-start

. Go to *Administration* > *Persistence*, and click *Force Start*.

. Confirm that you want to continue by clicking *Confirm* in the dialog.

A success message is displayed or, if an exception occurs, an error notification.