= Installing and starting Management Center
:page-aliases: ROOT:getting-started.adoc
:description: You can install Management Center, using Docker, a package manager, or the binary distribution.

{description}

== Before you begin

xref:overview.adoc#requirements[Review the requirements] to make sure that you meet them.

== Use Docker

Deploying via Docker is a convenient way to evaluate the latest version of Management Center:

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Management Center Docker image from Docker Hub.
+
ifdef::snapshot[]
[source,bash]
----
docker pull hazelcast/management-center:latest
----
. Start the Management Center service.
+
[source,shell,subs="attributes+"]
----
docker run --rm -p 8080:8080 hazelcast/management-center:latest
----
endif::[]
ifndef::snapshot[]
[source,bash,subs="attributes+"]
----
docker pull hazelcast/management-center:{full-version}
----
. Start the Management Center service.
+
[source,shell,subs="attributes+"]
----
docker run --rm -p 8080:8080 hazelcast/management-center:{full-version}
----
endif::[]

In some cases, such as querying maps that contain custom objects, you may need to add those object classes to the classpath of Management Center before starting it. To add your own classes to the classpath, you can do one of the following:

- Pass the `MC_CLASSPATH` environment variable the paths to your classes, separated by a semicolon.
- Put your classes in the `bin/user-lib/` directory, and mount that directory to the Docker container.

You can find more details on link:https://hub.docker.com/r/hazelcast/management-center[DockerHub].

== Use a package manager

Hazelcast offers package managers for Linux and Mac operating systems.

// tag::cli[]
. To install Management Center, use one of the following methods, depending on your operating system:
+
[tabs] 
==== 
Mac:: 
+ 
--

To install on macOS, use the Homebrew package manager.
[source,bash,subs="attributes+"]
----
brew tap hazelcast/hz
brew install hazelcast-management-center@{full-version}
----
--

Linux::
+
--

To install on Linux, you can use either of these package managers, depending on your Linux distribution:
ifdef::snapshot[]
.Debian
[source,shell]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
echo "deb https://repository.hazelcast.com/debian snapshot main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast-management-center
----

.RPM
[source,shell]
----
wget https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo -O hazelcast-snapshot-rpm.repo
sudo mv hazelcast-snapshot-rpm.repo /etc/yum.repos.d/
sudo yum install hazelcast-management-center
----
endif::[]
ifndef::snapshot[]
.Debian
[source,shell,subs="attributes+"]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
echo "deb https://repository.hazelcast.com/debian stable main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast-management-center={full-version}
----

.RPM
[source,shell,subs="attributes+"]
----
wget https://repository.hazelcast.com/rpm/stable/hazelcast-rpm-stable.repo -O hazelcast-rpm-stable.repo
sudo mv hazelcast-rpm-stable.repo /etc/yum.repos.d/
sudo yum install hazelcast-management-center={full-version}
----
endif::[]
--
Windows::
+
--
At the moment, Management Center does not support any Windows package managers.

To get started with Management Center on Windows, use one of the other available installation options.
--
====

. Check that Management Center is installed.
+
[source,shell]
----
hz-mc -V
----
+
You should see the version of Management Center.
// end::cli[]

For more information about the package manager, see the link:https://github.com/hazelcast/hazelcast-management-center-packaging[GitHub repository].

[[binary]]
== Use binary packages

Hazelcast Management Center is included in the Hazelcast Platform download package.

When a new version of Hazelcast Platform is released, it comes with a compatible version of Management Center. You can download Hazelcast Platform from the https://hazelcast.com/open-source-projects/downloads/#hazelcast-platform[download page]
of the Hazelcast website.

If a new version of Management Center is released before a new
version of Hazelcast Platform, you can download the new version as a
separate package
from the https://hazelcast.com/open-source-projects/downloads/#hazelcast-management-center[download page].

To start Management Center from the binary package, use the scripts that come with the download package.

NOTE: You cannot use Management Center as a library. Management Center runs as a standalone web application.

You can preconfigure a cluster connection in Management Center by setting the following environment variables:

* `MC_DEFAULT_CLUSTER_MEMBERS`—this should contain a comma-separated list of the cluster member addresses.
* `MC_DEFAULT_CLUSTER`—this should contain the cluster name, and defaults to `dev` if not provided.

The recommended way to start Management Center with the binary package is the built-in start scripts in the `bin/` directory. A script is available as a batch file for Windows or a shell script for Mac and Linux.

You can start this file from the command line using the following command:

[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
hz-mc start
----
--
Windows::
+
[source,shell,subs="attributes+"]
----
mc-start.cmd 
----
====

[[starting-with-an-extra-classpath]]
== Provide an extra classpath
In some cases, such as querying maps that contain custom objects, you may need to add those object classes to the classpath of Management Center before starting it. To add your own classes to the classpath, do one of the following:

- Pass the `MC_CLASSPATH` environment variable the paths to your classes, separated by semicolons.
- Put your classes in the `bin/user-lib/` directory.

[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
export MC_CLASSPATH="/path/to/an/extra.jar:/path/to/an/otherextra.jar"
hz-mc start
----
--

Windows::
+
--
[source,shell,subs="attributes+"]
----
SET MC_CLASSPATH="/path/to/an/extra.jar;/path/to/an/otherextra.jar"
mc-start.cmd 
----
--
====


== Stop Management Center via the command line
The following command stops all Management Center processes that are started with either `hz-mc start` or `mc-start.cmd` commands:
[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
hz-mc stop
----
--

Windows::
+
--
[source,shell,subs="attributes+"]
----
mc-stop.cmd
----
--
====
NOTE: These commands stop Management Center processes that have exactly the same version as the script. If you have multiple versions of Management Center running,
you need to stop each version using its corresponding script.

== Snapshot versions

Development versions of an upcoming release are available as snapshots. To use the most recent snapshot version of Management Center, do the following:

- Docker:
+
[source,bash,subs="attributes+"]
----
docker run --rm -p 8080:8080 --pull=always hazelcast/management-center:latest
----

- Binary packages:
** link:https://download.hazelcast.com/management-center/management-center-latest-snapshot.zip[Download ZIP]
** link:https://download.hazelcast.com/management-center/management-center-latest-snapshot.tar.gz[Download TAR]

- Package managers:
** Homebrew
+
[source,bash,subs="attributes+"]
----
brew tap hazelcast/hz
brew install hazelcast-management-center@{full-version}
----
** Linux
+
.Debian
[source,shell]
----
wget -qO - https://repository.hazelcast.com/api/gpg/key/public | sudo apt-key add -
echo "deb https://repository.hazelcast.com/debian snapshot main" | sudo tee -a /etc/apt/sources.list
sudo apt update && sudo apt install hazelcast-management-center
----
+
.RPM
[source,shell]
----
wget https://repository.hazelcast.com/rpm/snapshot/hazelcast-rpm.repo -O hazelcast-snapshot-rpm.repo
sudo mv hazelcast-snapshot-rpm.repo /etc/yum.repos.d/
sudo yum install hazelcast-management-center
----


When you use a snapshot version, it can be useful to query the build information to be able to tell what revision you are using.
You can find version metadata about a running instance of Management Center at the following endpoint: `<hazelcast.mc.home>/api/buildInfo`. This endpoint returns JSON.

== Next steps

For guidance on how to get up and running quickly, see xref:get-started.adoc[].

To learn how to connect to a cluster, see xref:deploy-manage:cluster-connections.adoc[].

To serve Management Center over HTTPS instead of HTTP, see xref:deploy-manage:serve-mc-over-https.adoc[].

For information about the options you can provide when starting Management Center, see xref:deploy-manage:system-properties.adoc[].

.Enterprise topics
[%collapsible]
====
To explore the licensed features of Management Center, see:

* xref:integrate:clustered-rest.adoc[Clustered REST]
* xref:integrate:jmx.adoc[Clustered JMX]
* xref:clusters:client-filtering.adoc[Cluster Client Filtering]
* xref:integrate:prometheus-monitoring.adoc[Prometheus Exporter]

For the Management Center features that rely on your cluster's enterprise capabilities, see:

* xref:clusters:wan-replication.adoc[WAN Replication]
* xref:clusters:persistence.adoc[Persistence]
* xref:clusters:triggering-rolling-upgrade.adoc[Rolling Upgrades]
====
