= Installing and Starting Management Center
:page-aliases: ROOT:getting-started.adoc
:description: This topic explains the options for installing and starting Management Center, using Docker or the binary packages.

{description}

== Before you Begin

xref:overview.adoc#requirements[Review the requirements] and make sure that you meet them.

== Using Docker

. link:https://docs.docker.com/get-docker/[Install Docker^].

. Check that Docker is correctly installed.
+
[source,bash]
----
docker version
----

. If you do not see a version number, see the link:https://docs.docker.com/config/daemon/[Docker docs^] for troubleshooting information.

. Pull the Management Center Docker image from Docker Hub.
+
[source,bash,subs="attributes+"]
----
docker pull hazelcast/management-center:{full-version}
----
. Start the Management Center service
+
[source,shell,subs="attributes+"]
----
docker run --rm -p 8080:8080 hazelcast/management-center:{full-version}
----

In some cases, such as querying maps that contain custom objects, you may need to add those object classes to the classpath of Management Center before starting it. To add your own classes to the classpath, you can do one of the following:

- Pass the `MC_CLASSPATH` environment variable the paths to your classes, separated by a semicolon.
- Put your classes in the `bin/user-lib/` directory, and mount that directory to the Docker container.

Please see more details at link:https://hub.docker.com/r/hazelcast/management-center[DockerHub].

== Using Binary Packages

Hazelcast Management Center is included in the Hazelcast Platform download package.

When a new version of Hazelcast Platform is released, it comes with a compatible version of Management Center. You can download Hazelcast Platform from the https://hazelcast.com/open-source-projects/downloads/#hazelcast-platform[download page]
of the Hazelcast website.

If a new version of Management Center is released before a new
version of Hazelcast Platform, you can download the new version as a
separate package
from the https://hazelcast.com/open-source-projects/downloads/#hazelcast-management-center[download page].

To start Management Center from the binary package, you have the following options:

* Use the JAR file.
* Use the scripts that come with the download package.
* Deploy the WAR file on your Java application's server/servlet container.

For all the starting options you can preconfigure a cluster in Management Center by setting the following environment variables:

* `MC_DEFAULT_CLUSTER_MEMBERS` variable should contain a comma-separated list of the cluster member addresses.
* `MC_DEFAULT_CLUSTER` variable should contain the cluster name and defaults to `dev` if not provided.

[[starting-with-scripts]]
=== Using Start Script

The recommended way to start Management Center with the binary package is the built-in `mc-start` script in the `bin/` directory. This script is available as a batch file for Windows or a shell script for Mac and Linux.

You can start this file from the command line using the following command:

[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
hz-mc start
----
--
Windows::
+
[source,shell,subs="attributes+"]
----
mc-start.cmd 
----
====

In some cases, such as querying maps that contain custom objects, you may need to add those object classes to the classpath of Management Center before starting it. To add your own classes to the classpath, you can do one of the following:

- Pass the `MC_CLASSPATH` environment variable the paths to your classes, separated by semicolons.
- Put your classes in the `bin/user-lib/` directory.

[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
export MC_CLASSPATH="/path/to/an/extra.jar:/path/to/an/otherextra.jar"
hz-mc start
----
--

Windows::
+
--
[source,shell,subs="attributes+"]
----
SET MC_CLASSPATH="/path/to/an/extra.jar;/path/to/an/otherextra.jar"
mc-start.cmd 
----
--
====


[[starting-with-jar-file]]
=== Using the JAR File

The download package contains a `hazelcast-management-center-{full-version}.jar` file, which you can execute directly from the command line using the following command.

WARNING: Some environment variables do not work with the JAR file. We recommend using the <<starting-with-scripts, script>>.

[source,bash,subs="attributes+"]
----
java -jar hazelcast-management-center-{full-version}.jar
----

In some cases, such as querying maps that contain custom objects, you may need to add those object classes to the classpath of Management Center before starting it. To add your own classes to the classpath, you can do the following:

[tabs]
====
Linux and Mac::
+
--
[source,bash,subs="attributes+"]
----
java -cp "hazelcast-management-center-{full-version}.jar:/path/to/an/extra.jar" com.hazelcast.webmonitor.Launcher
----
--

Windows::
+
--
[source,shell,subs="attributes+"]
----
java -cp "hazelcast-management-center-{full-version}.jar;/path/to/an/extra.jar" com.hazelcast.webmonitor.Launcher
----
--
====

[[deploying-to-application-server]]
=== Deploying to an Application Server

The download package contains a `hazelcast-management-center-{full-version}.war` file, which you can deploy on your application server, such as Tomcat or Jetty.

== SNAPSHOT versions

Development versions of an upcoming release are available as snapshots. To use the most recent snapshot version of Management Center, use the `latest-snapshot` tag in Docker:

[source,bash,subs="attributes+"]
----
docker run --rm -p 8080:8080 --pull=always hazelcast/management-center:latest-snapshot
----

Alternatively, you can download the latest snapshot package:
- link:https://download.hazelcast.com/management-center/management-center-latest-snapshot.zip[Download ZIP]
- link:https://download.hazelcast.com/management-center/management-center-latest-snapshot.tar.gz[Download TAR]

In these cases, it can be useful to query the build information to be able to tell what revision you are using.
You can find version metadata about a running instance of Management Center at the following endpoint: `<hazelcast.mc.home>/api/buildInfo`. This endpoint returns JSON.

== Next Steps

For an end-to-end getting started, see xref:get-started.adoc[].

To learn how to connect to a cluster, see xref:deploy-manage:cluster-connections.adoc[].

To serve Management Center over HTTPS instead of HTTP, see xref:deploy-manage:serve-mc-over-https.adoc[].

For the options you can provide when starting Management Center, see xref:deploy-manage:system-properties.adoc[].

.Enterprise topics
[%collapsible]
====
To explore the licensed features of Management Center, see the following:

* xref:integrate:clustered-rest.adoc[Clustered REST]
* xref:integrate:jmx.adoc[Clustered JMX]
* xref:clusters:client-filtering.adoc[Cluster Client Filtering]
* xref:integrate:prometheus-monitoring.adoc[Prometheus Exporter]

See also the following for the Management Center features that rely on your cluster's enterprise capabilities:

* xref:clusters:wan-replication.adoc[WAN Replication]
* xref:clusters:persistence.adoc[Persistence]
* xref:clusters:triggering-rolling-upgrade[Rolling Upgrades]
====
