= Management Center {full-version}
:page-aliases: ROOT:index.adoc
:description: Management Center is a tool for managing and monitoring Hazelcast Platform clusters.

{description}

Here are some example of what you can do with Management Center:

* Monitor the performance of your clusters from the UI, a JMX interface, and Prometheus.
* See statistical information about your members, clients, and data structures.
* Execute SQL queries on your clusters.
* Perform administrative tasks such as identifying and diagnosing issues in clusters.
* Use client filtering to define rules of which clients are allowed (or denied) to connect to a cluster as part of Blue/Green or Red/Black deployments.
* Use REST API endpoints to return the information presented in Management Center. 

[[os-requirements]]
== Requirements

You must meet the following requirements to be able to run Management Center

=== Supported Java Virtual Machines

Hazelcast supports the latest and long-term support (LTS) versions of the Java Development Kit (JDK). However, the JVM in some JDKs may not be compatible with Hazelcast.

Management Center {full-version} has been tested against the following JDKs.

TIP: If you install Hazelcast with Docker or a package manager, it comes with a supported JDK.

include::{page-latest-supported-hazelcast}@hazelcast:deploy:versioning-compatibility.adoc[tag=supported-jvms]

=== Mac and Windows System Requirements

Management Center uses the RocksDB library to store metrics
data on disk. Because of this dependency, Mac and Windows users must do one of the following:

* Use the official Management Center docker image.
* xref:deploy-manage:historical-metrics.adoc#disabling-metrics-persistence[Disable metrics persistence].
* Meet the following requirements:
** Mac: Use at least version 10.15 version of Catalina.
** Windows: Install the Microsoft Visual C++ 2015 redistributable.

=== Linux System Requirements

Most Linux distributions are supported, assuming that `glibc` 2.12 or newer is installed.

Experimental support for AIX is provided as well, with the following prerequisites:

* AIX version is 7.2 or newer
* https://www.ibm.com/support/pages/aix-toolbox-linux-applications-overview[AIX Toolbox] is installed
* `glibc` version is 2.17 or newer
* JRE 1.8 or newer is installed
* `libsnappy` 1.8.0 or newer is installed

=== Hazelcast Cluster Compatibility

Management Center supports the following versions of Hazelcast:

[cols="1a,1a"]
|===
|Product
|Supported versions

|Hazelcast Platform
|
5.1.x

5.0.x

|Hazelcast IMDG
|4.2.x

|===

[[browser-compatibility]]
== Browser Compatibility

Management Center supports the following browsers:

* Last two versions of Chrome at the time of release
* Last two versions of Firefox at the time of release
* Latest Safari
* Internet Explorer 11
* Latest Microsoft Edge

== Licensing

A valid Enterprise license for Management Center is required for the following features:

* Clustered JMX
* Clustered REST API
* Cluster client filtering
* Prometheus exporter
* Configuration healthcheck

A valid Enterprise license for Hazelcast members is required for the following features:

* WAN replication
* Persistence (Hot Restart)
* Rolling upgrade

If you do not have a license, you can use non-licensed features to monitor clusters of up to a maximum of three members.

If a page in the documentation requires an Enterprise license, it is labelled [.enterprise]*Enterprise*.

== Support

Support is provided via the following channels:

* xref:ROOT:troubleshooting.adoc[Troubleshooting page] of this guide
* https://stackoverflow.com/questions/tagged/hazelcast[Stack Overflow]
(ask a question about how to use Management Center properly and troubleshoot your setup)
* https://groups.google.com/forum/#!forum/hazelcast[Hazelcast mailing list]
(propose features and discuss your ideas with the team)
* https://slack.hazelcast.com/[Hazelcast community Slack]
(discuss anything related to Hazelcast and Management Center with other
Hazelcast users and Hazelcast developers)

== Get Started

xref:get-started.adoc[].
