= Management Center {full-version}
:page-aliases: ROOT:index.adoc
:description: Management Center is a powerful tool for managing and monitoring Hazelcast Platform clusters.

{description}

Management Center provides a user-friendly interface to monitor performance, view statistics, and perform administrative tasks.

== Key Features and Benefits

* *Monitoring and Performance Tracking*. Management Center allows you to monitor the performance of your clusters through its UI, JMX interface, and Prometheus integration. You can view detailed statistics about members, clients, and data structures in real-time, helping you identify performance bottlenecks and optimize your applications.
* *Execute SQL queries on your clusters*. The SQL Browser feature enables you to execute SQL queries on your clusters. Management Center shows queryable objects with a schema and index explorer, and can handle streaming SQL queries, displaying the last 1,000 entries as they arrive.
* *Administrative Capabilities*. Management Center enables you to perform various administrative tasks such as:
** Identifying and diagnosing issues in clusters
** Implementing client filtering to control which clients can connect to a cluster
** Executing scripts to automate interactions with the cluster
** Taking thread dumps from nodes
** Updating map configurations 
* *High Availability*. Management Center supports high availability deployments where multiple Management Center instances can connect to the same cluster, eliminating a single point of failure for management and monitoring purposes. 
User Management with Role-Based Access Control. Management Center provides comprehensive role-based access control with different user roles (Admin, User, Read-Only, and Metrics-Only) having varying levels of permissions for different operations.
* *Easy Deployment with Docker*. You can quickly get started with Management Center using Docker Compose. For example, you can create a `docker-compose.yml` file to run both Hazelcast and Management Center containers, with Management Center automatically connecting to the Hazelcast cluster. 
* *REST API and Integration*. Management Center offers REST API endpoints to programmatically access the information presented in the UI, making it easier to integrate with other systems and automate monitoring and management tasks. 
Using Management Center, you can manage your Hazelcast deployment, and quickly respond to any issues that may arise.

[[os-requirements]]
== Requirements

You must meet the following requirements to be able to run Management Center.

=== Supported Java Virtual Machines

Hazelcast supports the latest and long-term support (LTS) versions of the Java Development Kit (JDK). However, the JVM in some JDKs may not be compatible with Hazelcast.

Management Center {full-version} has been tested against the following JDKs.

TIP: If you install Hazelcast with Docker or a package manager, it comes with a supported JDK.

include::{page-latest-supported-hazelcast}@hazelcast:deploy:versioning-compatibility.adoc[tag=supported-jvms]

=== Mac and Windows System Requirements

Management Center uses the RocksDB library to persist metrics
to disk. Because of this dependency, Mac and Windows users must do one of the following:

* Use the official Management Center docker image.
* xref:deploy-manage:historical-metrics.adoc#disabling-metrics-persistence[Disable metrics persistence].
* Meet the following requirements:
** Mac: Use at least version 10.15 version of Catalina.
** Windows: Install the Microsoft Visual C++ 2015 redistributable.

=== Linux System Requirements

Most Linux distributions are supported, assuming that `glibc` 2.12 or newer is installed.

Experimental support for AIX with Metrics Persistence disabled is provided.

=== Hazelcast Cluster Compatibility

Management Center supports the following versions of Hazelcast:

[cols="1a,1a"]
|===
|Product
|Supported versions

|Hazelcast Platform
|
5.5.x

5.4.x

5.3.x

5.2.x

5.1.x

5.0.x

|Hazelcast IMDG
|4.2.x

|===

[[browser-compatibility]]
== Browser Compatibility

Management Center supports the following browsers:

* Last two versions of Chrome at the time of release
* Last two versions of Firefox at the time of release
* Latest Safari
* Latest Microsoft Edge

NOTE: Internet Explorer 11 is no longer supported.

== Licensing

A valid Enterprise license for Management Center is required for some features. 
For a list of Enterprise features, see xref:deploy-manage:license-management.adoc[Licensed Features].

A valid Enterprise license for Hazelcast members is required for the following features:

* WAN replication
* Persistence (Hot Restart)
* Rolling upgrade

If you do not have a license, you can use non-licensed features to monitor clusters of up to a maximum of three members.

If a page in the documentation requires an Enterprise license, it is labelled [.enterprise]*Enterprise*.

[[support]]
== Getting Support

Hazelcast provides two types of support: one for the Community Edition, and one for the Enterprise Edition.

=== Community Support

Community support is for every Hazelcast user. You can use the following channels to get community support:

* xref:ROOT:troubleshooting.adoc[Troubleshooting page] of this guide
* https://slack.hazelcast.com/[Hazelcast community Slack]
(here you can discuss anything related to Hazelcast and Management Center with the Hazelcast community)

=== Customer Support

Customer support is for Hazelcast Enterprise Edition customers.
See https://hazelcast.com/services/support/[hazelcast.com^] for the support options.
A support subscription from Hazelcast will allow you to get the most value out of your
selection of Hazelcast. Our customers benefit from rapid response times to technical
support inquiries, access to critical software patches, and other services which
will help you achieve increased productivity and quality. Learn more about Hazelcast support subscriptions:
https://hazelcast.com/pricing/

If your organization subscribes to Hazelcast support,
and you already have an account setup, you can login to your account and open
a support request using our ticketing system:  https://support.hazelcast.com/s/.

When submitting a ticket to the team, please provide as much information and data as possible:

* Make sure that all your environments are capturing Hazelcast diagnostics logs.
This a primary on diagnosing issues with Hazelcast environments.
* If your environments are not capturing diagnostics logs, please update them to capture diagnostics logs.
* Make note of your issue with a clear description of the issue for a title text.
This will allow the team to route the issue to the proper expert
* Make a note of the steps to reproduce if possible.
If not please capture the sequence of events that led to the problem.
* Write a complete description of the problem along with any error found.
* Capture any relevant screen shots and or errors noted.
* Create a support ticket on https://support.hazelcast.com/s/[Hazelcast Support Portal].
* Attach the appropriate severity to the ticket.
* `PROD` issues that affect production are considered as severity 1.
* All other issues in other environments are considered severity 2 or 3 depending on urgency.
* `DEV` issues are considered as severity 3 and priority low.
* All other issues, e.g., questions or documentation review are considered as severity 3 or higher.

==== Adding Details to the Support Ticket

* When you open a support ticket add a concise title and description of the problem.
* Add steps to reproduce as best as you can document them so that support can attempt
to reproduce the problem. This includes Detailed description of incident – what happened and when.
* Add a reproducible test case, this is optional - Hazelcast engineering may ask for it if required.
* Add details of use case. This is crucial as it helps support narrow down the features and
functionality in play when the problem occurred.
* Attach any specific errors found.
* Attach the complete logs files, i.e., Hazelcast logs.
* Attach Hazelcast process logs.
* Attach Hazelcast health monitor logs.
* Attach thread dumps from all members.
* Add networking logs.
* Specify the time of incident.
* When providing Hazelcast logs, please make sure that the system and
environment details that are captured at system startup are included, even if you truncate the logs.
* Add Hazelcast diagnostic logs. Please do not truncate diagnostics logs. They only capture Hazelcast
systems specific information and details.
* Please make sure that the logs capture data around the date and time of the incident.

Please consider the above for prompt help from the team and note that the more information
is provided upfront the better.
Lastly, be prompt in your communication with Hazelcast support - helps to ensure timely resolution of issues.

== Get Started

xref:get-started.adoc[].
