= Management Center {full-version}
:page-aliases: ROOT:index.adoc
:description: Hazelcast Management Center provides a powerful and intuitive interface for managing and monitoring your Hazelcast Platform clusters.

{description}

Using Management Center, you can manage your Hazelcast deployment with a user-friendly interface to monitor performance, view statistics, and perform administrative tasks, allowing you to respond quickly to any issues that may arise, and helping you maximize the value of your Hazelcast deployment.

== {enterprise-product-name} versus {open-source-product-name}

While the {open-source-product-name} offers basic functionality for small deployments (up to 3 cluster members), the {enterprise-product-name} unlocks the full potential of Management Center with advanced security, monitoring, and management features. Get a 30-day free trial with no obligation from our https://hazelcast.com/get-started/[Try Hazelcast] page.

To access Enterprise features, an Enterprise license must be installed on Management Center. See xref:deploy-manage:license-management.adoc[].

NOTE: For information about xref:{page-latest-supported-hazelcast}@hazelcast:ROOT:whats-new.adoc[What's new], see the Hazelcast Platform documentation.

[[os-requirements]]
== Requirements

You must meet the following requirements to be able to run Management Center.

=== Supported Java Virtual Machines

Hazelcast supports the latest and long-term support (LTS) versions of the Java Development Kit (JDK). However, the JVM in some JDKs may not be compatible with Hazelcast.

Management Center {full-version} has been tested against the following JDKs.

TIP: If you install Hazelcast with Docker or a package manager, it comes with a supported JDK.

include::{page-latest-supported-hazelcast}@hazelcast:deploy:versioning-compatibility.adoc[tag=supported-jvms]

=== Mac and Windows system requirements

Management Center uses the RocksDB library to persist metrics
to disk. Because of this dependency, Mac and Windows users must do one of the following:

* Use the official Management Center docker image.
* xref:deploy-manage:historical-metrics.adoc#disabling-metrics-persistence[Disable metrics persistence].
* Meet the following requirements:
** Mac: use at least version 10.15 version of Catalina.
** Windows: install the Microsoft Visual C++ 2015 redistributable.

=== Linux system requirements

Most Linux distributions are supported, assuming that `glibc` 2.12 or newer is installed.

Experimental support for AIX with Metrics Persistence disabled is provided.

=== Hazelcast cluster compatibility

Management Center supports the following versions of Hazelcast:

[cols="1a,1a"]
|===
|Product
|Supported versions

|Hazelcast Platform
|
5.5.x

5.4.x

5.3.x

5.2.x

5.1.x

5.0.x

|Hazelcast IMDG
|4.2.x

|===

[[browser-compatibility]]
== Browser compatibility

Management Center supports the following browsers:

* Last two versions of Chrome at the time of release
* Last two versions of Firefox at the time of release
* Latest Safari
* Latest Microsoft Edge

NOTE: Internet Explorer 11 is no longer supported.

== Licensing

A valid Enterprise license for Management Center is required for some features. 
For a list of Enterprise features, see xref:deploy-manage:license-management.adoc[Licensed Features].

A valid Enterprise license for Hazelcast members is required for the following features:

* WAN replication
* Persistence (Hot Restart)
* Rolling upgrade

If you do not have a license, you can use non-licensed features to monitor clusters of up to a maximum of three members.

If a feature in the documentation requires an Enterprise license, it is labelled [.enterprise]*Enterprise*.

[[support]]
== Get support

For information about the types of support Hazelcast offers, see xref:get-support.adoc[Get support].

== Next steps

For guidance on how to get up and running quickly with Management Center, see xref:get-started.adoc[].
