name: Backport changes to maintenance branches
on:
 push:
  branches:
   - main
jobs:
  backport-to-specified-branch:
    strategy:
      fail-fast: false
      matrix:
        branch: ['5.0', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6', '5.7']
    uses: hazelcast/hz-docs/.github/workflows/backport-workflow.yml@main
    with:
      label-to-check-for: '["backport to ${{ matrix.branch }}"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit
